"use client";
import {useEffect,useState} from "react";
import {getCustomerCases,getCustomerCaseActivity,getCustomerCaseActions,addCustomerCaseActivity,setApiToken,type CustomerCase} from "../../../lib/api";

export default function CustomerCases(){
 const [cases,setCases]=useState<CustomerCase[]>([]); const [selected,setSelected]=useState<CustomerCase|null>(null);
 const [activity,setActivity]=useState<any[]>([]); const [actions,setActions]=useState<any[]>([]); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false);
 async function load(){setLoading(true);setError("");try{const r=await getCustomerCases();setCases(r.cases);if(selected){const n=r.cases.find(x=>x.case_id===selected.case_id);if(n)setSelected(n)}}catch(e){setError(e instanceof Error?e.message:"Unable to load cases")}finally{setLoading(false)}}
 useEffect(()=>{setApiToken(sessionStorage.getItem("cyclothone_access_token")||"");void load()},[]);
 async function select(c:CustomerCase){setSelected(c);setActivity([]);setActions([]);try{const [r,a]=await Promise.all([getCustomerCaseActivity(c.case_id),getCustomerCaseActions(c.case_id)]);setActivity(r.activity);setActions(a.actions)}catch(e){setError(e instanceof Error?e.message:"Unable to load case activity")}}
 return <main className="cyclo-water min-h-screen overflow-hidden text-[#e8eef6]"><div className="relative z-10 mx-auto max-w-7xl px-5 py-8 md:px-8 md:py-12">
  <div className="flex items-center justify-between"><div><a href="/customer/workspace" className="cyclo-pill inline-flex px-3 py-2 text-[10px] text-[#9ab0b6]">← Customer workspace</a><h1 className="mt-2 text-2xl font-semibold">Security cases</h1><p className="mt-1 text-xs text-[#728093]">Live cases linked to your organization service requests.</p></div><button onClick={()=>void load()} className="cyclo-pill px-3 py-2 text-[10px] text-[#c2f35a]">Refresh</button></div>
  {error&&<div className="mt-4 rounded-2xl border border-[#ff2d55]/40 bg-[#250910]/50 p-4 text-xs text-[#ff6b83]">{error}</div>}
  <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_1.25fr]">
   <section className="cyclo-stage overflow-hidden">{loading?<div className="p-5 text-xs text-[#728093]">Loading…</div>:cases.length?cases.map(c=><button key={c.case_id} onClick={()=>void select(c)} className={"block w-full border-b border-white/10 p-4 text-left transition "+(selected?.case_id===c.case_id?"bg-[#c2f35a]/[.06]":"hover:bg-white/[.025]")}><div className="flex justify-between gap-3"><span className="font-mono text-xs">{c.case.case_number}</span><span className="text-[9px] uppercase text-[#00d9ff]">{c.case.status}</span></div><div className="mt-2 text-sm">{c.case.title}</div><div className="mt-1 text-[10px] text-[#728093]">{c.service_request?.service_key} · {c.case.severity}</div></button>):<div className="p-5 text-xs text-[#728093]">No cases are currently linked to this organization.</div>}</section>
   <section className="cyclo-stage p-6">{selected?<><div className="flex justify-between"><div><div className="font-mono text-xs">{selected.case.case_number}</div><h2 className="mt-2 text-lg">{selected.case.title}</h2></div><span className="h-fit border border-[#2a3646] px-2 py-1 text-[9px]">{selected.case.category} · {selected.case.severity}</span></div><div className="mt-4 border-b border-[#1a2330] pb-4 text-xs leading-5 text-[#9aa7b7]">{selected.case.summary}</div><h3 className="mt-5 text-xs">Response actions</h3><div className="mt-3 space-y-2">{actions.map(a=><div key={a.id} className="border border-[#1a2330] p-3"><div className="flex justify-between text-[9px] uppercase"><span>{a.action}</span><span>{a.status}</span></div><div className="mt-1 text-[9px] text-[#5a6675]">{a.created_at?new Date(a.created_at).toLocaleString():""}</div></div>)}{!actions.length&&<div className="text-xs text-[#728093]">No response actions recorded.</div>}</div><h3 className="mt-5 text-xs">Activity</h3><div className="mt-3 space-y-3">{activity.map(a=><div key={a.id} className="border-l border-[#2a3646] pl-3"><div className="text-[9px] uppercase text-[#5a6675]">{a.event_type} · {a.actor_type}</div><div className="mt-1 text-xs">{a.message}</div><div className="mt-1 text-[9px] text-[#5a6675]">{new Date(a.created_at).toLocaleString()}</div></div>)}{!activity.length&&<div className="text-xs text-[#728093]">No activity recorded.</div>}</div><div className="mt-5 border-t border-[#1a2330] pt-4"><div className="text-xs">Send an update to the security team</div><div className="mt-2 flex gap-2"><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={2} placeholder="Describe new information, evidence, or a question…" className="min-w-0 flex-1 rounded-2xl border border-white/10 bg-[#031019]/80 p-3 text-xs outline-none focus:border-[#c2f35a]/40"/><button disabled={busy||!message.trim()} onClick={async()=>{if(!selected)return;setBusy(true);setError("");try{await addCustomerCaseActivity(selected.case_id,message.trim());setMessage("");const r=await getCustomerCaseActivity(selected.case_id);setActivity(r.activity)}catch(e){setError(e instanceof Error?e.message:"Unable to record update")}finally{setBusy(false)}}} className="self-end rounded-full border border-[#c2f35a]/50 bg-[#c2f35a]/10 px-4 py-2 text-[10px] text-[#ddff9a] disabled:opacity-40">{busy?"Sending…":"Send"}</button></div></div></>:<div className="flex h-full min-h-64 items-center justify-center text-xs text-[#728093]">Select a case.</div>}</section>
  </div>
 </div></main>
}
