"use client";

import {useEffect,useMemo,useState} from "react";
import {AuthActions} from "@/components/AuthActions";
import {getCustomerCases,getCustomerOrganizations,getCustomerServiceRequests,type CustomerCase,type CustomerOrganization,type CustomerServiceRequest} from "../../../lib/api";

const SERVICES=[["cybersecurity_assessment","Cybersecurity Assessment","#5ccbc3"],["incident_response","Incident Response","#ff3d67"],["threat_intelligence","Threat Intelligence","#ff5b64"],["web_intelligence","Web Intelligence","#39d7ff"],["scam_monitoring","Scam Monitoring","#ffb52e"],["dark_web_monitoring","Dark Web Monitoring","#9b6cff"],["brand_protection","Brand Protection","#ff9d32"],["soc_mdr","SOC / MDR","#6de7a1"],["ai_security","AI Security","#3c9dff"],["physical_security","Physical Security","#ffd34e"],["compliance","Compliance","#54e38a"],["hunting","Threat Hunting","#ff8a3d"],["investigation","Investigation","#4aa8ff"],["recovery","Recovery","#55e6a1"],["mobile_digital_intelligence","Mobile & Digital Intelligence","#38a8ff"]] as const;
const tone:Record<string,string>={approved:"text-[#9ff5c0]",verified:"text-[#9ff5c0]",pending:"text-[#ffd27a]",submitted:"text-[#ffd27a]",in_progress:"text-[#ffd27a]",resolved:"text-[#9ff5c0]",closed:"text-[#9ff5c0]",rejected:"text-[#ff7c93]"};

export default function CustomerOverview(){
 const [orgs,setOrgs]=useState<CustomerOrganization[]>([]),[requests,setRequests]=useState<CustomerServiceRequest[]>([]),[cases,setCases]=useState<CustomerCase[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{void(async()=>{try{const[o,r,c]=await Promise.all([getCustomerOrganizations(),getCustomerServiceRequests(),getCustomerCases()]);setOrgs(o.organizations);setRequests(r.service_requests);setCases(c.cases)}catch(e){setError(e instanceof Error?e.message:"Unable to load customer command center")}finally{setLoading(false)}})()},[]);
 const org=orgs[0]??null;
 const active=requests.filter(r=>["submitted","triage","accepted","in_progress","blocked"].includes(r.status));
 const recent=useMemo(()=>requests.slice().sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,4),[requests]);
 return <main className="cyclo-water min-h-screen overflow-hidden text-[#e8f1f3]">
  <header className="relative z-10 flex flex-wrap items-center justify-between gap-4 border-b border-white/10 bg-[#02090e]/70 px-5 py-4 backdrop-blur-2xl">
   <div className="flex items-center gap-3"><a href="/" className="cyclo-mark text-lg font-bold">◌</a><div><a href="/" className="font-semibold tracking-tight">CYCLOTHONE</a><span className="ml-3 text-[9px] uppercase tracking-[.18em] text-[#789aa4]">Customer</span></div></div>
   <nav className="flex flex-wrap gap-2 text-[10px]"><a href="/customer/services" className="cyclo-pill px-3 py-2 text-[#c2f35a]">Services</a><a href="/customer/workspace" className="cyclo-pill px-3 py-2 text-[#9ab0b6]">Command Center</a><a href="/customer/cases" className="cyclo-pill px-3 py-2 text-[#9ab0b6]">Cases</a><a href="/customer/profile" className="cyclo-pill px-3 py-2 text-[#9ab0b6]">Profile</a><AuthActions/></nav>
  </header>
  <div className="relative z-10 mx-auto max-w-7xl px-5 py-9 md:px-8">
   <div className="flex flex-wrap items-end justify-between gap-6"><div><div className="text-[9px] uppercase tracking-[.22em] text-[#4f8494]">Security Command Center</div><h1 className="mt-3 text-3xl font-semibold tracking-tight md:text-5xl">{org?.legal_name||"Your security environment"}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-[#8ca6ad]">Explore, request and follow security work from one place. Your account is already authenticated. Organization controls appear when a protected workflow needs them.</p></div><div className="cyclo-orb hidden h-24 w-24 md:block"/></div>
   {error&&<div className="mt-6 rounded-2xl border border-[#ff3d67]/30 bg-[#250910]/50 p-4 text-xs text-[#ff8ba0]">{error}</div>}
   {loading?<div className="mt-8 p-10 text-center text-xs text-[#69858d]">Reading your live security environment…</div>:<>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Active workflows",String(active.length),"live requests"],["Results / cases",String(cases.length),"security cases"],["Services",String(SERVICES.length),"available capabilities"],["Workspace",org?org.admission_status:"not created","organization state"]].map(([a,b,c])=><div key={a} className="cyclo-stage p-5"><div className="text-[9px] uppercase tracking-[.16em] text-[#5c7b84]">{a}</div><div className={"mt-3 text-2xl font-medium "+(a==="Workspace"?(tone[b]??"text-[#c2f35a]"):"")}>{b}</div><div className="mt-1 text-[10px] text-[#66838c]">{c}</div></div>)}</section>
    {!org&&<div className="mt-5 rounded-[2rem] border border-[#c2f35a]/15 bg-[#c2f35a]/[.035] p-5"><div className="text-[9px] uppercase tracking-[.18em] text-[#c2f35a]">Browse first · protect when needed</div><p className="mt-2 max-w-2xl text-xs leading-6 text-[#8ca6ad]">Every service is available to explore now. Creating an organization is not required to understand the platform; it is only required when a protected service workflow needs an organizational security boundary.</p><a href="/customer/services" className="mt-3 inline-block text-[10px] text-[#c2f35a]">Explore all services →</a></div>}
    {org&&active.length>0&&<section className="mt-8 cyclo-stage p-6"><div className="flex items-center justify-between"><div><div className="text-[9px] uppercase tracking-[.18em] text-[#4f8494]">Now</div><h2 className="mt-1 text-lg">Active security work</h2></div><a href="/customer/cases" className="text-[10px] text-[#c2f35a]">View cases →</a></div><div className="mt-5 space-y-3">{active.slice(0,4).map(r=><a key={r.id} href={"/customer/services/"+encodeURIComponent(r.service_key)} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/10 bg-black/10 p-4"><div><div className="text-xs">{SERVICES.find(s=>s[0]===r.service_key)?.[1]||r.service_key}</div><div className="mt-1 text-[10px] text-[#66838c]">{r.description}</div></div><div className={"text-[9px] uppercase tracking-wider "+(tone[r.status]||"text-[#8ca6ad]")}>{r.status.replaceAll("_"," ")}</div></a>)}</div></section>}
    <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-[9px] uppercase tracking-[.2em] text-[#4f8494]">Capability map</div><h2 className="mt-1 text-2xl font-semibold">Security services</h2><p className="mt-2 text-xs text-[#8ca6ad]">Choose a service to understand the question, workflow, evidence and result before you start.</p></div><a href="/customer/services" className="cyclo-pill px-4 py-2 text-[10px] text-[#c2f35a]">Full catalog →</a></div>
     <div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{SERVICES.map(([key,name,accent],i)=><a key={key} href={"/customer/services/"+encodeURIComponent(key)} className="cyclo-node group min-h-[205px] p-5"><div className="relative z-10 flex items-start justify-between"><div><div className="font-mono text-[9px] text-[#4e707b]">{String(i+1).padStart(2,"0")}</div><h3 className="mt-2 font-medium">{name}</h3></div><span className="text-lg text-[#c2f35a] transition-transform group-hover:translate-x-1">↗</span></div><div className="relative z-10 mt-10 flex items-center gap-2 text-[9px] uppercase tracking-[.16em]" style={{color:accent}}><span className="cyclo-signal">●</span> Operational surface</div><div className="relative z-10 mt-4 text-[10px] text-[#66838c]">{requests.filter(r=>r.service_key===key).length} request(s) · {cases.filter(c=>c.service_request?.service_key===key).length} case(s)</div></a>)}</div>
    </section>
    {org&&<section className="mt-8 grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><div className="cyclo-stage p-6"><div className="flex items-center justify-between"><h2 className="text-lg">Recent activity</h2><a href="/request-service" className="text-[10px] text-[#c2f35a]">+ New workflow</a></div>{recent.length?<div className="mt-4 space-y-2">{recent.map(r=><div key={r.id} className="flex items-center justify-between gap-3 border-b border-white/10 py-3 text-xs"><span>{SERVICES.find(s=>s[0]===r.service_key)?.[1]||r.service_key}</span><span className={tone[r.status]||"text-[#8ca6ad]"}>{r.status}</span></div>)}</div>:<p className="mt-4 text-xs text-[#66838c]">No protected workflows have been requested yet.</p>}</div><div className="cyclo-stage p-6"><div className="text-[9px] uppercase tracking-[.18em] text-[#4f8494]">Protected workspace</div><h2 className="mt-2 text-lg">{org.admission_status}</h2><p className="mt-2 text-xs leading-5 text-[#66838c]">Organization, assurance and membership controls stay in the command center.</p><a href="/customer/workspace" className="mt-4 inline-block text-[10px] text-[#c2f35a]">Open command center →</a></div></section>}
   </>}
  </div>
 </main>
}