"use client";

import { useEffect, useMemo, useState } from "react";

type Detection = { id: string; tenant_id: string; device_id: string; event_id: string | null; detector: string; score: number; verdict: string; reasons: string[]; evidence?: Record<string, unknown>; mitre_technique: string | null; created_at: string; processed_by_playbooks: boolean; processed_by_autocase: boolean };
type Result = { items: Detection[]; total: number; limit: number; offset: number };
const API = process.env.NEXT_PUBLIC_SENTINEL_API_URL ?? "";
function requestHeaders(token: string): HeadersInit { const value = token.trim(); return value ? { Authorization: `Bearer ${value}` } : {}; }
function tone(value: string): string { const v = value.toLowerCase(); if (v === "block" || v === "critical") return "border-[#ff2d55]/40 bg-[#ff2d55]/10 text-[#ff2d55]"; if (v === "quarantine" || v === "high") return "border-[#ffb020]/40 bg-[#ffb020]/10 text-[#ffb020]"; if (v === "monitor" || v === "medium") return "border-[#4a9eff]/40 bg-[#4a9eff]/10 text-[#4a9eff]"; return "border-[#2a3646] bg-[#111823] text-[#8a97a8]"; }

export default function ThreatsPage() {
  const [token, setToken] = useState(""); const [items, setItems] = useState<Detection[]>([]); const [total, setTotal] = useState(0); const [offset, setOffset] = useState(0); const [selected, setSelected] = useState<Detection | null>(null); const [q, setQ] = useState(""); const [detector, setDetector] = useState(""); const [verdict, setVerdict] = useState(""); const [minScore, setMinScore] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const limit = 50;

  const load = async (nextOffset = 0) => { setLoading(true); setError(null); try { const params = new URLSearchParams({ limit: String(limit), offset: String(nextOffset), sort: "created_at", direction: "desc" }); if (detector.trim()) params.set("detector", detector.trim()); if (verdict) params.set("verdict", verdict); if (minScore.trim()) params.set("min_score", minScore.trim()); const response = await fetch(`${API}/api/v1/console/threats?${params.toString()}`, { headers: requestHeaders(token), cache: "no-store" }); if (!response.ok) throw new Error(response.status === 401 ? "Authentication required" : response.status === 403 ? "console:read scope required" : `API ${response.status}`); const body = (await response.json()) as Result; setItems(body.items ?? []); setTotal(body.total ?? 0); setOffset(body.offset ?? nextOffset); setSelected(null); } catch (err) { setError(err instanceof Error ? err.message : "Unable to reach Sentinel API"); } finally { setLoading(false); } };
  useEffect(() => { void load(0); }, []);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); document.getElementById("threat-search")?.focus(); } if (event.key === "Escape") setSelected(null); if (!items.length || ["INPUT", "SELECT"].includes((event.target as HTMLElement | null)?.tagName ?? "")) return; const index = selected ? items.findIndex(item => item.id === selected.id) : -1; if (event.key === "ArrowDown") { event.preventDefault(); setSelected(items[Math.min(index + 1, items.length - 1)]); } if (event.key === "ArrowUp") { event.preventDefault(); setSelected(items[Math.max(index - 1, 0)]); } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [items, selected]);
  const visible = useMemo(() => { const needle = q.trim().toLowerCase(); if (!needle) return items; return items.filter(item => [item.id, item.device_id, item.event_id, item.detector, item.verdict, item.mitre_technique, ...item.reasons].some(value => String(value ?? "").toLowerCase().includes(needle))); }, [items, q]);

  return <main className="min-h-screen bg-[#05070a] text-[#e8eef6]">
    <header className="sticky top-0 z-10 flex h-12 items-center border-b border-[#1a2330] bg-[#0a0e14] px-4"><a href="/" className="font-semibold">◈ Sentinel</a><span className="ml-5 font-mono text-[10px] text-[#5a6675]">OPERATIONS / THREATS</span><span className="ml-auto font-mono text-[10px] text-[#5a6675]">⌘K focus · ↑↓ select · Esc close</span></header>
    <section className="p-5">
      <div className="mb-4 flex items-end justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.16em] text-[#5a6675]">Detection control plane</div><h1 className="mt-1 text-2xl font-semibold">Threats / Detections</h1></div><div className="font-mono text-[11px] text-[#8a97a8]">{total.toLocaleString()} total</div></div>
      <div className="mb-4 grid grid-cols-[minmax(260px,1fr)_180px_150px_120px_auto] gap-2"><input id="threat-search" aria-label="Search detections" value={q} onChange={event => setQ(event.target.value)} placeholder="Search IDs, devices, detectors, MITRE…" className="h-9 border border-[#2a3646] bg-[#0a0e14] px-3 font-mono text-[11px] outline-none focus:border-[#00d9ff]" /><input aria-label="Detector" value={detector} onChange={event => setDetector(event.target.value)} placeholder="Detector" className="h-9 border border-[#2a3646] bg-[#0a0e14] px-3 font-mono text-[11px] outline-none focus:border-[#00d9ff]" /><select aria-label="Verdict" value={verdict} onChange={event => setVerdict(event.target.value)} className="h-9 border border-[#2a3646] bg-[#0a0e14] px-3 font-mono text-[11px]"><option value="">All verdicts</option><option value="block">block</option><option value="quarantine">quarantine</option><option value="monitor">monitor</option><option value="allow">allow</option></select><input aria-label="Minimum score" value={minScore} onChange={event => setMinScore(event.target.value)} inputMode="decimal" placeholder="Min score" className="h-9 border border-[#2a3646] bg-[#0a0e14] px-3 font-mono text-[11px] outline-none focus:border-[#00d9ff]" /><button onClick={() => void load(0)} className="h-9 border border-[#00d9ff] px-4 text-[11px] text-[#00d9ff]">Apply</button></div>
      {error && <div role="alert" className="mb-4 border border-[#ff2d55]/40 bg-[#ff2d55]/5 p-3 text-[12px] text-[#ff2d55]">{error}<div className="mt-2 flex gap-2"><input aria-label="Access token" type="password" value={token} onChange={event => setToken(event.target.value)} placeholder="Access token (memory only)" className="w-80 border border-[#2a3646] bg-[#030508] px-2 py-1.5 font-mono text-[11px]" /><button onClick={() => void load(0)} className="border border-[#ff2d55]/50 px-3 py-1.5">Retry</button></div></div>}
      <div className="overflow-hidden border border-[#1a2330] bg-[#0a0e14]"><div className="grid grid-cols-[24px_190px_140px_100px_110px_1fr_150px] border-b border-[#1a2330] bg-[#111823] px-3 py-2 text-[9px] uppercase tracking-[.12em] text-[#5a6675]"><span /><span>Detection</span><span>Device</span><span>Score</span><span>Verdict</span><span>Detector / MITRE</span><span>Created</span></div>{loading && <div className="p-8 text-center font-mono text-[11px] text-[#5a6675]">Loading detections…</div>}{!loading && visible.length === 0 && <div className="p-10 text-center"><div className="font-mono text-[12px] text-[#8a97a8]">No detections returned</div><div className="mt-1 text-[11px] text-[#5a6675]">No synthetic rows are generated.</div></div>}{!loading && visible.map(item => <button key={item.id} onClick={() => setSelected(item)} className={`grid w-full grid-cols-[24px_190px_140px_100px_110px_1fr_150px] border-b border-l-2 border-[#1a2330] px-3 py-3 text-left text-[11px] hover:bg-[#111823] ${selected?.id === item.id ? "border-l-[#00d9ff] bg-[#111823]" : "border-l-transparent"}`}><span className="text-[#5a6675]">›</span><span className="truncate font-mono" title={item.id}>{item.id}</span><span className="truncate font-mono text-[#8a97a8]" title={item.device_id}>{item.device_id}</span><span className="font-mono">{item.score.toFixed(3)}</span><span><span className={`inline-flex rounded border px-1.5 py-0.5 font-mono text-[9px] uppercase ${tone(item.verdict)}`}>{item.verdict}</span></span><span className="min-w-0"><span className="block truncate">{item.detector}</span><span className="font-mono text-[9px] text-[#5a6675]">{item.mitre_technique ?? "MITRE —"}</span></span><span className="font-mono text-[10px] text-[#8a97a8]">{new Date(item.created_at).toISOString()}</span></button>)}</div>
      <div className="mt-3 flex items-center justify-between font-mono text-[10px] text-[#5a6675]"><span>Showing {total ? offset + 1 : 0}–{Math.min(offset + limit, total)} of {total}</span><div className="flex gap-2"><button disabled={offset === 0 || loading} onClick={() => void load(Math.max(0, offset - limit))} className="border border-[#2a3646] px-3 py-1.5 disabled:opacity-30">Prev</button><button disabled={offset + limit >= total || loading} onClick={() => void load(offset + limit)} className="border border-[#2a3646] px-3 py-1.5 disabled:opacity-30">Next</button></div></div>
    </section>
    {selected && <aside aria-label="Detection detail" className="fixed inset-y-0 right-0 z-20 w-[460px] overflow-auto border-l border-[#2a3646] bg-[#0a0e14] shadow-2xl"><div className="sticky top-0 flex items-center justify-between border-b border-[#1a2330] bg-[#0a0e14] px-4 py-3"><div><div className="text-[10px] uppercase tracking-[.14em] text-[#5a6675]">Detection detail</div><div className="mt-1 font-mono text-[11px]">{selected.id}</div></div><button onClick={() => setSelected(null)} aria-label="Close detail">×</button></div><div className="space-y-5 p-4 text-[11px]"><div className="grid grid-cols-2 gap-2"><div className="border border-[#1a2330] p-3"><div className="text-[#5a6675]">Score</div><div className="mt-1 font-mono text-xl">{selected.score.toFixed(3)}</div></div><div className="border border-[#1a2330] p-3"><div className="text-[#5a6675]">Verdict</div><div className="mt-2"><span className={`rounded border px-1.5 py-0.5 font-mono text-[9px] uppercase ${tone(selected.verdict)}`}>{selected.verdict}</span></div></div></div><dl className="space-y-3">{[["Detector", selected.detector], ["Device", selected.device_id], ["Event", selected.event_id ?? "—"], ["MITRE technique", selected.mitre_technique ?? "—"], ["Created", new Date(selected.created_at).toISOString()], ["AutoCase", selected.processed_by_autocase ? "processed" : "pending"], ["Playbooks", selected.processed_by_playbooks ? "processed" : "pending"]].map(([label, value]) => <div key={label}><dt className="text-[#5a6675]">{label}</dt><dd className="mt-1 break-all font-mono">{value}</dd></div>)}</dl><div><h2 className="mb-2 text-[10px] uppercase tracking-[.14em] text-[#5a6675]">Reasons</h2><ul className="space-y-1">{selected.reasons.map((reason, index) => <li key={`${selected.id}-${index}`} className="border-l border-[#2a3646] pl-3">{reason}</li>)}</ul></div>{selected.evidence && <div><h2 className="mb-2 text-[10px] uppercase tracking-[.14em] text-[#5a6675]">Evidence</h2><pre className="max-h-80 overflow-auto border border-[#1a2330] bg-[#030508] p-3 font-mono text-[10px] text-[#8a97a8]">{JSON.stringify(selected.evidence, null, 2)}</pre></div>}</div></aside>}
  </main>;
}
