"use client";

import { useEffect, useMemo, useState } from "react";
import { getOverview, setApiToken } from "../lib/api";

type FeedItem = { id:string; device_id:string|null; detector:string; score:number|null; verdict:string|null; reasons:string[]|null; created_at:string; mitre_technique?:string|null };
type Overview = { generated_at:string; agents:{total:number}; threats:{last_24h:number;previous_24h:number;delta_percent:number|null}; critical:{count:number}; uptime_percent:number|null; response_p95_ms:number|null; coverage:Record<string,{observed:number}|null>; feed:FeedItem[] };
type IconName="shield"|"radar"|"bolt"|"globe"|"phone"|"eye"|"fingerprint"|"badge"|"brain"|"scroll"|"rewind"|"search"|"nodes"|"terminal"|"settings"|"bell"|"chevron";

const groups=[["OPERATIONS",[["Overview","shield"],["Threats","radar"],["Detection","radar"],["Response","bolt"]]],["INTELLIGENCE",[["Web Intel","globe"],["Scam","phone"],["Dark Web","eye"],["Brand","fingerprint"]]],["CONVERGENCE",[["Physical","badge"],["AI Security","brain"]]],["ASSURANCE",[["Compliance","scroll"],["Recovery","rewind"],["Hunting","search"]]],["PLATFORM",[["Federation","nodes"],["Developer","terminal"],["Customer Workspace","shield"],["Admin Admissions","badge"],["Settings","settings"]]]] as const;
const paths:Record<IconName,string>={shield:"M12 3l7 3v5c0 4.6-3 8.5-7 10-4-1.5-7-5.4-7-10V6l7-3z M9 12l2 2 4-5",radar:"M12 12h.01 M4.9 4.9a10 10 0 0114.2 0 M7.8 7.8a6 6 0 018.4 0 M12 12l5-5",bolt:"M13 2L4 14h6l-1 8 9-12h-6l1-8z",globe:"M12 3a9 9 0 100 18 9 9 0 000-18z M3 12h18 M12 3c2.2 2.4 3.3 5.4 3.3 9S14.2 18.6 12 21c-2.2-2.4-3.3-5.4-3.3-9S9.8 5.4 12 3z",phone:"M6 3h4l2 5-3 2a14 14 0 006 6l2-3 5 2v4c0 1-1 2-2 2C11 21 3 13 3 4c0-1 1-1 3-1z M16 8l5-5 M21 8V3h-5",eye:"M3 12s3.5-6 9-6 9 6 9 6-3.5 6-9 6-9-6-9-6z M4 4l16 16",fingerprint:"M12 11a3 3 0 013 3v6 M8 20v-6a4 4 0 018 0v2 M6 18v-4a6 6 0 0112 0 M4 16v-2a8 8 0 0116 0",badge:"M12 3l3 2 3-.2.8 3 2.2 2.2 2.2-2.2 2.2-.8 3-3-.2-3 2-3-2-3 .2-.8-3L4.8 10 7 7.8l.8-3L11 5l1-2z M9 12l2 2 4-4",brain:"M9 4a3 3 0 00-3 3v1a3 3 0 00-2 5 3 3 0 002 5v1a3 3 0 003 3 M15 4a3 3 0 013 3v1a3 3 0 012 5 3 3 0 01-2 5v1a3 3 0 01-3 3 M9 8h6 M9 16h6 M12 4v16",scroll:"M7 4h10v16H7a2 2 0 010-4h10 M7 4a2 2 0 000 4h10 M10 12h4 M10 15h3",rewind:"M9 7H4l5-5 M4 7a8 8 0 111.5 9 M9 12h7 M13 9l3 3-3 3",search:"M10.5 4a6.5 6.5 0 104.6 11.1L20 20 M10.5 7v7 M7 10.5h7",nodes:"M6 6h.01 M18 6h.01 M12 18h.01 M6 6l6 12 6-12 M6 6h12",terminal:"M4 5h16v14H4z M7 9l3 3-3 3 M12 15h4",settings:"M12 8a4 4 0 100 8 4 4 0 000-8z M4 12h2m12 0h2M12 4v2m0 12v2M6.3 6.3l1.4 1.4m8.6 8.6l1.4 1.4m0-11.4l-1.4 1.4m-8.6 8.6l-1.4 1.4",bell:"M18 8a6 6 0 00-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9 M10 21h4",chevron:"M9 18l6-6-6-6"};
function Icon({name}:{name:IconName}){return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4"><path d={paths[name]}/></svg>}
function Stat({label,value,meta,bad=false}:{label:string;value:string;meta:string;bad?:boolean}){return <div className="border-r border-[#1a2330] px-5 last:border-0"><div className={"font-mono text-[32px] font-bold leading-none "+(bad?"bg-gradient-to-br from-[#ff2d55] to-[#ff7a1a] bg-clip-text text-transparent":"text-[#e8eef6]")}>{value}</div><div className="mt-2 text-[11px] font-medium uppercase tracking-[.12em] text-[#5a6675]">{label}</div><div className="mt-1 font-mono text-[11px] text-[#8a97a8]">{meta}</div></div>}
function Coverage({label,count,ratio}:{label:string;count:number|null;ratio?:number|null}){const width=ratio==null?0:Math.max(0,Math.min(100,ratio));return <div className="grid grid-cols-[140px_1fr_80px] items-center gap-3 py-1.5"><span className="text-[12px] text-[#8a97a8]">{label}</span><div className="h-1 overflow-hidden rounded-full bg-[#030508]"><div className="h-full bg-[#4a9eff] transition-[width] duration-200" style={{width:`${width}%`}}/></div><span className="text-right font-mono text-[11px] text-[#8a97a8]">{count==null?"—":count.toLocaleString()}</span></div>}
function verdictTone(v:string|null){const x=(v??"").toLowerCase();return x==="block"?"text-[#ff2d55] border-[#ff2d55]/40 bg-[#ff2d55]/10":x==="quarantine"?"text-[#ffb020] border-[#ffb020]/40 bg-[#ffb020]/10":x==="monitor"?"text-[#4a9eff] border-[#4a9eff]/40 bg-[#4a9eff]/10":"text-[#8a97a8] border-[#2a3646] bg-[#111823]"}

export default function Home(){
 const [data,setData]=useState<Overview|null>(null),[error,setError]=useState<string|null>(null),[token,setToken]=useState(""),[collapsed,setCollapsed]=useState(false),[palette,setPalette]=useState(false),[query,setQuery]=useState("");
 const load=async()=>{try{const r=await fetch(`${apiBase}/api/v1/console/overview`,{headers:token?{Authorization:`Bearer ${token}`}:{} ,cache:"no-store"});if(!r.ok)throw new Error(r.status===401?"Authentication required":r.status===403?"console:read scope required":`API ${r.status}`);setData(await r.json());setError(null)}catch(e){setError(e instanceof Error?e.message:"Unable to reach Cyclothone API")}};
 useEffect(()=>{if(typeof window!=="undefined"){const saved=sessionStorage.getItem("cyclothone_access_token")??"";setToken(saved)}void load()},[]);useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(true);setQuery("")}if((e.metaKey||e.ctrlKey)&&e.key==="\\"){e.preventDefault();setCollapsed(v=>!v)}if(e.key==="Escape")setPalette(false)};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h)},[]);
 const delta=useMemo(()=>data?.threats.delta_percent==null?"—":`${data.threats.delta_percent>0?"+":""}${data.threats.delta_percent}%`,[data]);
 const feed=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return data?.feed??[];return (data?.feed??[]).filter(x=>[x.detector,x.verdict,x.device_id,...(x.reasons??[]),x.mitre_technique].some(v=>(v??"").toLowerCase().includes(q)))},[data,query]);
 const suggestions=["critical detections","executive overview","response queue","device"];
 return <main className="flex h-screen min-w-0 flex-col overflow-hidden bg-[#05070a] text-[#e8eef6]">
  <header className="flex h-12 shrink-0 items-center border-b border-[#1a2330] bg-[#0a0e14] px-4"><div className="flex w-[240px] shrink-0 items-center gap-2"><Icon name="shield"/><span className="font-semibold tracking-tight" >Cyclothone</span><span className="rounded border border-[#00d9ff] px-1.5 py-0.5 font-mono text-[10px] text-[#00d9ff]">ae-1</span></div><button aria-label="Open command palette" onClick={()=>setPalette(true)} className="mx-auto flex h-7 w-[440px] items-center gap-2 rounded border border-[#2a3646] bg-[#030508] px-3 text-left text-[12px] text-[#5a6675] hover:border-[#3a4a5e]"><Icon name="search"/><span>Search detections, devices, cases, IOCs…</span><kbd className="ml-auto rounded border border-[#2a3646] px-1.5 py-0.5 font-mono text-[10px]">⌘K</kbd></button><div className="ml-auto flex w-[240px] items-center justify-end gap-4 text-[#8a97a8]"><button aria-label="Notifications" className="relative"><Icon name="bell"/><span aria-label="3 unread notifications" className="absolute -right-2 -top-1 min-w-3 rounded-full bg-[#ff2d55] px-1 text-center text-[8px] leading-3 text-white">3</span></button><span className="font-mono text-[10px]">OPS</span><span aria-hidden="true" className="h-6 w-6 rounded-full border border-[#2a3646] bg-[#111823] text-center text-[10px] leading-6">B</span></div></header>
  <div className="flex min-h-0 flex-1"><aside className={(collapsed?"w-[56px]":"w-[240px]")+" shrink-0 overflow-hidden border-r border-[#1a2330] bg-[#0a0e14] transition-[width] duration-150"}><nav aria-label="Primary navigation" className="px-2 py-3">{groups.map(([group,items])=><div key={group} className="mb-4"><div className="mb-1 px-2 text-[9px] font-semibold tracking-[.16em] text-[#5a6675]">{collapsed?"·":group}</div>{items.map(([label,icon],i)=><a key={label} href={label==="Overview"?"/":label==="Threats"?"/threats":label==="Detection"?"/detection":label==="Response"?"/response":label==="Web Intel"?"/intelligence/web":label==="Scam"?"/intelligence/scam":label==="Dark Web"?"/intelligence/dark-web":label==="Brand"?"/intelligence/brand":label==="Physical"?"/convergence/physical":label==="AI Security"?"/convergence/ai":label==="Compliance"?"/assurance/compliance":label==="Recovery"?"/assurance/recovery":label==="Hunting"?"/assurance/hunting":label==="Federation"?"/platform/federation":label==="Developer"?"/platform/developer":label==="Customer Workspace"?"/customer/workspace":label==="Admin Admissions"?"/admin/admissions":"/platform/settings"} title={label} aria-current={label==="Overview"?"page":undefined} className={(label==="Overview"?"border-[#00d9ff] bg-[#111823] text-[#00d9ff]":"border-transparent text-[#8a97a8]")+" mb-0.5 flex h-8 w-full items-center gap-3 rounded-r border-l-2 px-3 text-[12px] hover:bg-[#111823]"}><Icon name={icon as IconName}/>{!collapsed&&<><span>{label}</span>{group==="OPERATIONS"&&i===1&&<span className="ml-auto rounded bg-[#ff2d55]/15 px-1.5 font-mono text-[9px] text-[#ff2d55]">—</span>}</>}</a>)}</div>)}</nav><div className={(collapsed?"text-center":"px-3")+" mt-auto pb-3 font-mono text-[9px] text-[#5a6675]"}>{collapsed?"AE":"region: ae-1 · strict residency"}</div></aside>
   <section className="min-w-0 flex-1 overflow-auto"><div className="border-b border-[#1a2330] px-6 py-4"><div className="flex items-center justify-between"><div><div className="text-[10px] uppercase tracking-[.16em] text-[#5a6675]">Operational posture</div><h1 className="mt-1 text-xl font-semibold tracking-tight">Executive Overview</h1><div className="mt-3 flex gap-2"><a href="/register" className="rounded border border-[#00d9ff] px-3 py-1.5 text-[11px] text-[#00d9ff]">Create account</a><a href="/request-service" className="rounded border border-[#2a3646] px-3 py-1.5 text-[11px] text-[#8a97a8]">Request a service</a><a href="/login" className="rounded border border-[#2a3646] px-3 py-1.5 text-[11px] text-[#8a97a8]">Sign in</a></div></div><div className="flex items-center gap-2"><span className="font-mono text-[10px] text-[#5a6675]">24h snapshot</span><button onClick={()=>void load()} title="Refresh overview" aria-label="Refresh overview" className="rounded border border-[#2a3646] px-2 py-1 text-[11px] text-[#8a97a8] hover:bg-[#111823]">↻</button></div></div></div>
    <div className="grid grid-cols-4 border-b border-[#1a2330] py-6"><Stat label="Agents" value={data?data.agents.total.toLocaleString():"—"} meta="registered devices"/><Stat label="Threats" value={data?data.threats.last_24h.toLocaleString():"—"} meta={`${delta} vs prior 24h`} bad={!!data?.threats.delta_percent&&data.threats.delta_percent>0}/><Stat label="Critical cases" value={data?data.critical.count.toLocaleString():"—"} meta="created in 24h" bad={!!data?.critical.count}/><Stat label="API uptime" value={data?.uptime_percent==null?"—":`${data.uptime_percent}%`} meta={data?.uptime_percent==null?"telemetry not reported":"current API telemetry"}/></div>
    {error&&<div role="alert" className="mx-6 mt-5 border border-[#ff2d55]/40 bg-[#ff2d55]/5 p-4 text-[12px]"><div className="flex items-center gap-2 text-[#ff2d55]"><span aria-hidden="true">◆</span><span>{error}</span></div><div className="mt-3 flex gap-2"><input aria-label="Access token" value={token} onChange={e=>setToken(e.target.value)} type="password" placeholder="Access token (kept in memory only)" className="w-72 border border-[#2a3646] bg-[#030508] px-2 py-1.5 font-mono text-[11px] outline-none focus:border-[#00d9ff]"/><button onClick={()=>{setApiToken(token);void load()}} className="border border-[#00d9ff] px-3 py-1.5 text-[11px] text-[#00d9ff]">Connect</button></div></div>}
    <div className="grid grid-cols-2 gap-4 p-6"><div className="border border-[#1a2330] bg-[#0a0e14] p-4"><div className="mb-3 flex items-center justify-between"><span className="text-[12px]">Recent detection scores</span><span className="font-mono text-[10px] text-[#5a6675]">derived from returned detections</span></div>{data?.feed.length?<div className="flex h-14 items-end gap-1" aria-label="Recent detection scores">{data.feed.slice(0,24).map((x,i)=>{const v=Math.max(2,Math.min(100,Math.round((x.score??0)*100)));return <div key={x.id} title={`${x.detector}: ${x.score??"—"}`} className="flex-1 bg-[#00d9ff]/50" style={{height:`${v}%`}}/>})}</div>:<div className="flex h-14 items-center text-[11px] text-[#5a6675]">No detection score history returned.</div>}</div><div className="border border-[#1a2330] bg-[#0a0e14] p-4"><div className="mb-3 flex items-center justify-between"><span className="text-[12px]">Response time · p95</span><span className="font-mono text-[11px] text-[#00d9ff]">{data?.response_p95_ms==null?"—":`${data.response_p95_ms}ms`}</span></div><div className="flex h-14 items-center border-t border-[#1a2330] text-[11px] text-[#5a6675]">{data?.response_p95_ms==null?"No response-latency telemetry is exposed by the current API.":"Current API p95 response latency."}</div></div></div>
    <div className="grid grid-cols-[1.05fr_.95fr] gap-4 px-6 pb-6"><div className="border border-[#1a2330] bg-[#0a0e14] p-4"><div className="mb-3 flex items-center justify-between"><span className="text-[12px] font-medium">Coverage across layers</span><span className="font-mono text-[10px] text-[#5a6675]">observed</span></div><Coverage label="Endpoints" count={data?.coverage.endpoints?.observed??null} ratio={data?.coverage.endpoints?100:null}/><Coverage label="Web · surface" count={data?.coverage.web_surface?.observed??null}/><Coverage label="Deep web" count={data?.coverage.deep_web?.observed??null}/><Coverage label="Dark web" count={data?.coverage.dark_web?.observed??null}/><Coverage label="Physical" count={data?.coverage.physical?.observed??null}/><Coverage label="AI agents" count={data?.coverage.ai_agents?.observed??null}/></div><div className="border border-[#1a2330] bg-[#0a0e14] p-4"><div className="mb-3 flex items-center justify-between text-[12px]"><span>Live threat feed</span><span className="flex items-center gap-1 font-mono text-[10px] text-[#00e07a]"><span className="live-dot h-1.5 w-1.5 rounded-full bg-[#00e07a]"/>API snapshot</span></div><div className="divide-y divide-[#1a2330]">{data?.feed.length?data.feed.map(x=><div key={x.id} className="feed-row grid grid-cols-[88px_1fr_54px] items-center gap-2 py-2 text-[11px]"><span className={("w-fit rounded border px-1.5 py-0.5 font-mono text-[9px] font-semibold uppercase ")+verdictTone(x.verdict)}>{x.verdict??"unknown"}</span><span className="truncate text-[#8a97a8]">{x.reasons?.[0]??x.detector}</span><time className="font-mono text-right text-[10px] text-[#5a6675] date">{new Date(x.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time></div>):<div className="py-10 text-center text-[11px] text-[#5a6675]">No detections returned by the API.</div>}</div></div></div>
    <div className="px-6 pb-6"><div className="border border-[#1a2330] bg-[#0a0e14] p-4"><div className="mb-3 flex items-center justify-between"><span className="text-[12px] font-medium">Detection activity</span><span className="font-mono text-[10px] text-[#5a6675]">{feed.length} matching rows</span></div><div className="flex items-center gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter returned detections by detector, verdict, device or reason…" className="w-full border border-[#2a3646] bg-[#030508] px-3 py-2 text-[11px] text-[#e8eef6] outline-none focus:border-[#00d9ff]"/><kbd className="border border-[#2a3646] px-2 py-1 font-mono text-[10px] text-[#5a6675]">/</kbd></div></div></div>
   </section></div><footer className="flex h-6 shrink-0 items-center justify-between border-t border-[#1a2330] bg-[#0a0e14] px-3 font-mono text-[10px] text-[#5a6675]"><span className="flex items-center gap-1"><span className="live-dot h-1.5 w-1.5 rounded-full bg-[#00e07a]"/>connected API</span><span>region: ae-1 · realtime transport not exposed by current API</span><span>{data?new Date(data.generated_at).toISOString().slice(11,19)+"Z":"—"}</span></footer>
  {palette&&<div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Command palette" onClick={()=>setPalette(false)}><div className="mx-auto mt-24 w-[600px] border border-[#2a3646] bg-[#0a0e14] shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center gap-2 border-b border-[#1a2330] p-4"><Icon name="search"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="> Search current overview data" className="w-full bg-transparent text-sm outline-none placeholder:text-[#5a6675]"/><kbd className="border border-[#2a3646] px-1.5 py-0.5 font-mono text-[10px] text-[#5a6675]">Esc</kbd></div><div className="p-3 text-[12px]"><div className="mb-2 px-2 text-[9px] tracking-[.16em] text-[#5a6675]">SUGGESTED</div>{suggestions.map(label=><button key={label} onClick={()=>{setQuery(label);setPalette(false)}} className="flex w-full items-center gap-3 rounded px-2 py-2 text-left text-[#8a97a8] hover:bg-[#111823] hover:text-[#e8eef6]"><Icon name="search"/><span>{label}</span><span className="ml-auto font-mono text-[10px] text-[#5a6675]">↵</span></button>)}</div></div></div>}
 </main>
}
