"use client";
import {useEffect,useState} from "react";
import {apiFetch} from "../../../lib/api";
type R=Record<string,any>;
export default function Response(){const[p,setP]=useState<R[]>([]),[r,setR]=useState<R[]>([]),[caseId,setCaseId]=useState(""),[playbook,setPlaybook]=useState(""),[dry,setDry]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
const load=()=>Promise.all([apiFetch<any>("/api/v1/console/response/playbooks"),apiFetch<any>("/api/v1/console/response/runs")]).then(([a,b])=>{setP(a.items||[]);setR(b.items||[])}).catch(e=>setMsg(e.message));
useEffect(()=>{void load()},[]);
async function run(){setBusy(true);setMsg("");try{if(!playbook||!caseId)throw new Error("Playbook and case ID are required.");await apiFetch("/api/v1/console/response/playbooks/"+playbook+"/runs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({case_id:caseId,dry_run:dry})});setMsg(dry?"Dry run accepted.":"Response run accepted.");await load()}catch(e){setMsg(e instanceof Error?e.message:"Run failed")}finally{setBusy(false)}}
return <main className="min-h-screen bg-[#05070a] p-6 text-[#e8eef6]"><div className="mx-auto max-w-6xl space-y-5"><header><div className="text-[10px] uppercase tracking-[.16em] text-[#5a6675]">Operations</div><h1 className="mt-1 text-2xl font-semibold">Response</h1><p className="mt-1 text-xs text-[#8a97a8]">Live playbooks, controlled execution and response history.</p></header><section className="border border-[#1a2330] bg-[#0a0e14] p-5"><h2 className="font-semibold">Run playbook</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><select value={playbook} onChange={e=>setPlaybook(e.target.value)} className="h-9 border border-[#2a3646] bg-[#030508] px-2 text-xs"><option value="">Select playbook</option>{p.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input value={caseId} onChange={e=>setCaseId(e.target.value)} placeholder="Case UUID" className="h-9 border border-[#2a3646] bg-[#030508] px-2 text-xs"/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={dry} onChange={e=>setDry(e.target.checked)}/> Dry run</label></div><button disabled={busy} onClick={()=>void run()} className="mt-3 h-9 border border-[#00d9ff] px-4 text-xs text-[#00d9ff]">{busy?"Running…":"Run"}</button>{msg&&<div className="mt-3 text-xs text-[#8a97a8]">{msg}</div>}</section><section className="border border-[#1a2330] bg-[#0a0e14] p-5"><h2 className="font-semibold">Playbooks ({p.length})</h2><pre className="mt-3 max-h-72 overflow-auto text-xs">{JSON.stringify(p,null,2)}</pre></section><section className="border border-[#1a2330] bg-[#0a0e14] p-5"><h2 className="font-semibold">Runs ({r.length})</h2><pre className="mt-3 max-h-96 overflow-auto text-xs">{JSON.stringify(r,null,2)}</pre></section></div></main>
}