"use client";
import {useEffect,useState} from "react";
import {getOperatorCustomerCases,setApiToken,transitionCustomerCase,assignCustomerCase} from "../../../lib/api";

export default function OperatorCases(){
 const [rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[status,setStatus]=useState(""),[reason,setReason]=useState(""),[operator,setOperator]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){setError("");try{const r=await getOperatorCustomerCases();setRows(r.cases);if(selected){setSelected(r.cases.find((x:any)=>x.case.id===selected.case.id)||null)}}catch(e){setError(e instanceof Error?e.message:"Unable to load operator cases")}}
 useEffect(()=>{setApiToken(sessionStorage.getItem("cyclothone_access_token")||"");void load()},[]);
 async function transition(){if(!selected)return;setBusy(true);try{await transitionCustomerCase(selected.case.id,status,reason);await load()}catch(e){setError(e instanceof Error?e.message:"Transition failed")}finally{setBusy(false)}}
 async function assign(){if(!selected||!operator.trim())return;setBusy(true);try{await assignCustomerCase(selected.case.id,operator.trim());setOperator("");await load()}catch(e){setError(e instanceof Error?e.message:"Assignment failed")}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[#05070a] text-[#e8eef6] p-5"><div className="mx-auto max-w-7xl">
 <div className="flex items-center justify-between"><div><a href="/admin/admissions" className="text-[10px] text-[#00d9ff]">← Admissions</a><h1 className="mt-2 text-2xl font-semibold">Operational customer cases</h1><p className="mt-1 text-xs text-[#728093]">Live tenant-scoped cases connected to customer service requests.</p></div><button onClick={()=>void load()} className="border border-[#2a3646] px-3 py-2 text-[10px]">Refresh</button></div>
 {error&&<div className="mt-4 border border-[#ff2d55]/40 p-3 text-xs text-[#ff6b83]">{error}</div>}
 <div className="mt-5 grid gap-5 lg:grid-cols-[420px_1fr]">
 <section className="border border-[#1a2330] bg-[#0a0e14]">{rows.length?rows.map(x=><button key={x.case.id} onClick={()=>{setSelected(x);setStatus(x.case.status)}} className={"block w-full border-b border-[#1a2330] p-4 text-left "+(selected?.case.id===x.case.id?"bg-[#111823]":"")}><div className="flex justify-between"><span className="font-mono text-xs">{x.case.case_number}</span><span className="text-[9px] uppercase text-[#00d9ff]">{x.case.status}</span></div><div className="mt-2 text-sm">{x.case.title}</div><div className="mt-1 text-[10px] text-[#728093]">{x.service_request?.service_key} · {x.case.severity}</div></button>):<div className="p-5 text-xs text-[#728093]">No customer cases.</div>}</section>
 <section className="border border-[#1a2330] bg-[#0a0e14] p-5">{selected?<><div className="font-mono text-xs">{selected.case.case_number}</div><h2 className="mt-2 text-xl">{selected.case.title}</h2><p className="mt-3 text-xs leading-5 text-[#9aa7b7]">{selected.case.summary}</p>
 <div className="mt-6 grid gap-4 md:grid-cols-2"><div><label className="text-[9px] uppercase text-[#5a6675]">Lifecycle status</label><select value={status} onChange={e=>setStatus(e.target.value)} className="mt-2 w-full border border-[#2a3646] bg-[#030508] p-2 text-xs"><option>open</option><option>investigating</option><option>contained</option><option>reported</option><option>closed</option></select><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3} placeholder="Status change reason" className="mt-2 w-full border border-[#2a3646] bg-[#030508] p-2 text-xs"/><button disabled={busy||status===selected.case.status} onClick={()=>void transition()} className="mt-2 border border-[#00d9ff] px-3 py-2 text-[10px] text-[#00d9ff] disabled:opacity-40">Apply status</button></div>
 <div><label className="text-[9px] uppercase text-[#5a6675]">Assign operator</label><input value={operator} onChange={e=>setOperator(e.target.value)} placeholder="Authenticated operator user UUID" className="mt-2 w-full border border-[#2a3646] bg-[#030508] p-2 text-xs"/><button disabled={busy||!operator.trim()} onClick={()=>void assign()} className="mt-2 border border-[#2a3646] px-3 py-2 text-[10px] disabled:opacity-40">Assign</button><div className="mt-4 text-[10px] text-[#728093]">Current assignment: {selected.assignment?.operator_user_id||"unassigned"}</div></div></div>
 <div className="mt-6 border-t border-[#1a2330] pt-4 text-[10px] text-[#5a6675]">Service request: {selected.service_request?.id}<br/>Organization: {selected.link?.organization_id}<br/>Created: {new Date(selected.case.created_at).toLocaleString()}</div>
 </>:<div className="flex min-h-80 items-center justify-center text-xs text-[#728093]">Select a case.</div>}</section></div></div></main>
}