export type Edge={src:string;dst:string;weight:number;confidence:number;kind:string}
export type Adj=Map<string,Map<string,{cost:number;weight:number;kind:string}>>
export function buildAdjacency(edges:Edge[],directed=false):Adj{const a:Adj=new Map();for(const e of edges){if(!a.has(e.src))a.set(e.src,new Map());a.get(e.src)!.set(e.dst,{cost:1/Math.max(e.weight*e.confidence,.001),weight:e.weight*e.confidence,kind:e.kind});if(!directed){if(!a.has(e.dst))a.set(e.dst,new Map());a.get(e.dst)!.set(e.src,{cost:1/Math.max(e.weight*e.confidence,.001),weight:e.weight*e.confidence,kind:e.kind});}}return a}
export function pageRank(a:Adj,it=40,d=.85){const n=[...a.keys()],r=new Map(n.map(x=>[x,1/Math.max(n.length,1)]));for(let k=0;k<it;k++){const nr=new Map(n.map(x=>[x,(1-d)/Math.max(n.length,1)]));for(const u of n){const es=a.get(u)!;const z=[...es.values()].reduce((s,e)=>s+e.weight,0)||1;for(const [v,e] of es)nr.set(v,(nr.get(v)??0)+d*(r.get(u)??0)*e.weight/z)}for(const [x,v] of nr)r.set(x,v)}return r}
export function shortestPath(a:Adj,from:string,to:string,minWeight=.05){const d=new Map([[from,0]]),prev=new Map<string,string>(),q=[from];while(q.length){q.sort((x,y)=>(d.get(x)??Infinity)-(d.get(y)??Infinity));const u=q.shift()!;if(u===to)break;for(const [v,e] of a.get(u)??[]){if(e.weight<minWeight)continue;const nd=(d.get(u)??Infinity)+e.cost;if(nd<(d.get(v)??Infinity)){d.set(v,nd);prev.set(v,u);q.push(v)}}}if(!d.has(to))return null;const path:string[]=[];for(let x=to;;){path.unshift(x);if(x===from)break;x=prev.get(x)!}const kinds:string[]=[];for(let i=1;i<path.length;i++)kinds.push(a.get(path[i-1])!.get(path[i])!.kind);return {path,kinds,cost:+d.get(to)!.toFixed(4)}}
function neigh(x:string,a:Adj){return new Set(a.get(x)?.keys()??[])}
export function jaccard(a:string,b:string,g:Adj){const A=neigh(a,g),B=neigh(b,g),u=new Set([...A,...B]);return u.size?[...A].filter(x=>B.has(x)).length/u.size:0}
export function adamicAdar(a:string,b:string,g:Adj){let s=0;for(const x of neigh(a,g)){if(neigh(b,g).has(x)){const d=(g.get(x)?.size??0);if(d>1)s+=1/Math.log(d)}}return s}
export function labelPropagation(g:Adj,it=60){const labels=new Map([...g.keys()].map(x=>[x,x]));for(let k=0;k<it;k++){let changed=false;for(const n of g.keys()){const counts=new Map<string,number>();for(const [v,e] of g.get(n)??[]){const l=labels.get(v)!;counts.set(l,(counts.get(l)??0)+e.weight)}const best=[...counts.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0];if(best&&best!==labels.get(n)){labels.set(n,best);changed=true}}if(!changed)break}return labels}
