export interface Tle{name:string;noradId:number;epoch:Date;inclination:number;raan:number;eccentricity:number;argPerigee:number;meanAnomaly:number;meanMotion:number;bstar:number;line1:string;line2:string}
const rad=(d:number)=>d*Math.PI/180;
export function parseTle(name:string,l1:string,l2:string):Tle{const noradId=Number(l1.slice(2,7));const yy=Number(l1.slice(18,20));const day=Number(l1.slice(20,32));const year=yy<57?2000+yy:1900+yy;const epoch=new Date(Date.UTC(year,0,1));epoch.setUTCDate(1);epoch.setUTCSeconds((day-1)*86400);const mm=Number(l2.slice(52,63));return {name,noradId,epoch,inclination:rad(Number(l2.slice(8,16))),raan:rad(Number(l2.slice(17,25))),eccentricity:Number('0.'+l2.slice(26,33).trim()),argPerigee:rad(Number(l2.slice(34,42))),meanAnomaly:rad(Number(l2.slice(43,51))),meanMotion:mm*2*Math.PI/86400,bstar:0,line1:l1,line2:l2}}
function pos(t:Tle,at:Date){const mu=398600.4418,dt=(at.getTime()-t.epoch.getTime())/1000,n=t.meanMotion,a=Math.cbrt(mu/(n*n)),M=t.meanAnomaly+n*dt;let E=M;for(let i=0;i<8;i++)E-= (E-t.eccentricity*Math.sin(E)-M)/(1-t.eccentricity*Math.cos(E));const x0=a*(Math.cos(E)-t.eccentricity),y0=a*Math.sqrt(1-t.eccentricity*t.eccentricity)*Math.sin(E),v=Math.atan2(y0,x0);const r=Math.hypot(x0,y0),u=t.argPerigee+v,cu=Math.cos(u),su=Math.sin(u),cO=Math.cos(t.raan),sO=Math.sin(t.raan),ci=Math.cos(t.inclination),si=Math.sin(t.inclination);return {x:r*(cO*cu-sO*su*ci),y:r*(sO*cu+cO*su*ci),z:r*(su*si),r}}
function ground(t:Tle,at:Date){const p=pos(t,at),theta=7.2921159e-5*(at.getTime()-Date.UTC(2000,0,1))/1000,lon=Math.atan2(p.y,p.x)-theta,lat=Math.atan2(p.z,Math.hypot(p.x,p.y));return {lat:lat*180/Math.PI,lon:((lon*180/Math.PI+540)%360)-180,altKm:p.r-6378.137}}
export function predictPasses(t:Tle,o:{lat:number;lon:number;altKm?:number},from:Date,hours:number,minElevation=5,stepMin=2){const out:any[]=[];let prev:any=null,start:any=null,maxEl=-90;for(let ms=0;ms<=hours*3600000;ms+=stepMin*60000){const at=new Date(from.getTime()+ms),g=ground(t,at),dlat=rad(g.lat-o.lat),dlon=rad(g.lon-o.lon),a=Math.sin(dlat/2)**2+Math.cos(rad(o.lat))*Math.cos(rad(g.lat))*Math.sin(dlon/2)**2,central=2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a)),el=Math.atan2(Math.max(0,g.altKm),6378.137*central)*180/Math.PI;if(el>=minElevation&&start===null){start=at;maxEl=el}else if(start&&el>=minElevation){maxEl=Math.max(maxEl,el)}else if(start&&el<minElevation){out.push({aos:start,los:at,tca:new Date((start.getTime()+at.getTime())/2),maxElevation:maxEl,minRangeKm:null,startAzimuth:null,endAzimuth:null});start=null;maxEl=-90}prev=el}return out}
export function footprintCovers(t:Tle,at:Date,lat:number,lon:number,radiusKm=0){const g=ground(t,at),dlat=rad(g.lat-lat),dlon=rad(g.lon-lon),a=Math.sin(dlat/2)**2+Math.cos(rad(lat))*Math.cos(rad(g.lat))*Math.sin(dlon/2)**2;return 6378.137*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))<=Math.max(radiusKm,Math.max(50,g.altKm*.15))}
export function groundFootprint(t:Tle,at:Date){const g=ground(t,at);return {center:{lat:g.lat,lon:g.lon},radiusKm:Math.max(50,g.altKm*.15)}}
export function imagingOpportunities(t:Tle,o:{lat:number;lon:number},from:Date,hours:number){return predictPasses(t,o,from,hours,10)}
