"use client";
import {useEffect,useState} from "react";
import type {FormEvent} from "react";
import {useRouter} from "next/navigation";
import {getCustomerOrganizations,getCustomerVerification,setApiToken,apiFetch,type CustomerOrganization} from "../../lib/api";

const SERVICES=[["cybersecurity_assessment","Cybersecurity Assessment"],["incident_response","Incident Response"],["threat_intelligence","Threat Intelligence"],["web_intelligence","Web Intelligence"],["scam_monitoring","Scam Monitoring"],["dark_web_monitoring","Dark Web Monitoring"],["brand_protection","Brand Protection"],["soc_mdr","SOC / MDR"],["ai_security","AI Security"],["physical_security","Physical Security"],["compliance","Compliance"],["hunting","Threat Hunting"],["investigation","Investigation"],["recovery","Recovery"],["mobile_digital_intelligence","Mobile & Digital Intelligence"]];

function Progress({value}:{value:number|null}){if(value===null)return null;return <div className="mt-5"><div className="mb-2 flex justify-between text-[9px] uppercase tracking-[.15em] text-[#67848d]"><span>Live workflow progress</span><span className="text-[#c2f35a]">{value}%</span></div><div className="cyclo-battery"><span style={{width:Math.max(0,Math.min(100,value))+"%"}}/></div></div>}

export default function RequestService(){
 const router=useRouter();
 const [orgs,setOrgs]=useState<CustomerOrganization[]>([]),[org,setOrg]=useState(""),[service,setService]=useState("cybersecurity_assessment"),[urgency,setUrgency]=useState("normal"),[description,setDescription]=useState(""),[verification,setVerification]=useState<any[]>([]),[error,setError]=useState<string|null>(null),[result,setResult]=useState<any>(null),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError(null);try{const r=await getCustomerOrganizations();setOrgs(r.organizations);const id=r.organizations[0]?.id||"";setOrg(id);if(id){const v=await getCustomerVerification(id);setVerification(v.verifications)}}catch(e){setError(e instanceof Error?e.message:"Unable to load organization")}finally{setLoading(false)}}
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get("service");if(requested&&SERVICES.some(x=>x[0]===requested))setService(requested);const t=sessionStorage.getItem("cyclothone_access_token")||"";if(!t){router.replace("/login");return}setApiToken(t);void load()},[]);
 async function selectOrg(id:string){setOrg(id);setError(null);try{const v=await getCustomerVerification(id);setVerification(v.verifications)}catch(e){setError(e instanceof Error?e.message:"Unable to load verification")}}
 async function requestAdmission(){setError(null);try{await apiFetch("/api/v1/customer/organizations/"+encodeURIComponent(org)+"/admission",{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"Admission request failed")}}
 async function submit(e:FormEvent){e.preventDefault();setError(null);setResult(null);try{const r=await apiFetch<any>("/api/v1/customer/service-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organization_id:org,service_key:service,urgency,description})});setResult(r);setDescription("")}catch(e){setError(e instanceof Error?e.message:"Service request failed")}}
 const current=orgs.find(x=>x.id===org);
 const progress=typeof result?.progress_percent==="number"?result.progress_percent:typeof result?.progress==="number"?result.progress:null;
 const stage=typeof result?.stage==="string"?result.stage:null;
 return <main className="cyclo-water min-h-screen overflow-hidden text-[#e8f1f3]">
  <header className="relative z-10 flex items-center justify-between border-b border-white/10 bg-[#02090e]/70 px-5 py-4 backdrop-blur-2xl"><div className="flex items-center gap-3"><a href="/customer/services" className="cyclo-mark text-lg font-bold">◌</a><a href="/customer/services" className="font-semibold tracking-tight">CYCLOTHONE</a></div><a href="/customer/services" className="cyclo-pill px-3 py-2 text-[10px] text-[#9ab0b6]">Back to services</a></header>
  <div className="relative z-10 mx-auto max-w-4xl px-5 py-10 md:py-14">
   <div className="text-[9px] uppercase tracking-[.22em] text-[#4f8494]">Controlled request</div><h1 className="mt-3 text-3xl font-semibold md:text-4xl">Start a security workflow.</h1><p className="mt-3 text-sm leading-7 text-[#8ca6ad]">Tell Cyclothone the outcome you need. The platform will route the request through the authorized service workflow. Progress is shown only when the live service returns a real stage or percentage.</p>
   {error&&<div className="mt-6 rounded-2xl border border-[#ff3d67]/30 bg-[#250910]/50 p-4 text-xs text-[#ff8ba0]">{error}</div>}
   {loading?<div className="mt-8 text-center text-xs text-[#69858d]">Reading organization state…</div>:!orgs.length?<div className="mt-8 rounded-[2rem] border border-dashed border-white/10 bg-[#031019]/70 p-9 text-center text-xs text-[#69858d]">No organization is available.<br/><a className="mt-3 inline-block text-[#c2f35a]" href="/customer/profile">Create one in Profile →</a></div>:
   <form onSubmit={submit} className="cyclo-node mt-8 p-6 shadow-[0_30px_100px_rgba(0,0,0,.35)] md:p-8">
    <label className="relative z-10 block text-xs font-medium">Organization<select required value={org} onChange={e=>void selectOrg(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-[#031019]/80 p-3.5 text-sm outline-none focus:border-[#c2f35a]/40">{orgs.map(o=><option key={o.id} value={o.id}>{o.legal_name} · {o.admission_status}</option>)}</select></label>
    <div className="cyclo-stage relative z-10 mt-4 p-4 text-xs text-[#8ca6ad]">Admission <strong className="text-[#e8f1f3]">{current?.admission_status}</strong> · Verification <strong className="text-[#e8f1f3]">{current?.verification_status}</strong>{current?.admission_status!=="approved"&&<div className="mt-3 text-[#ffd27a]">The workspace must be admitted before a protected request can be created. <a href="/customer/workspace" className="text-[#c2f35a]">View workspace →</a></div>}</div>
    <div className="cyclo-stage relative z-10 mt-4 p-4 text-xs text-[#8ca6ad]">Verification records: {verification.length?verification.map(v=>v.verification_type+":"+v.status).join(" · "):"none"}</div>
    <label className="relative z-10 mt-5 block text-xs font-medium">Service<select value={service} onChange={e=>setService(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-[#031019]/80 p-3.5 text-sm outline-none focus:border-[#c2f35a]/40">{SERVICES.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label>
    <label className="relative z-10 mt-5 block text-xs font-medium">Urgency<select value={urgency} onChange={e=>setUrgency(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-[#031019]/80 p-3.5 text-sm outline-none focus:border-[#c2f35a]/40">{["low","normal","high","critical"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label className="relative z-10 mt-5 block text-xs font-medium">What do you need?<textarea required minLength={10} maxLength={10000} value={description} onChange={e=>setDescription(e.target.value)} rows={7} className="mt-2 w-full rounded-2xl border border-white/10 bg-[#031019]/80 p-4 text-sm leading-6 outline-none focus:border-[#c2f35a]/40" placeholder="Describe the outcome you need Cyclothone to secure, investigate, monitor or assess." /></label>
    {result&&<div className="relative z-10 mt-5 rounded-2xl border border-[#c2f35a]/25 bg-[#b8ee4a]/5 p-5"><div className="text-[9px] uppercase tracking-[.18em] text-[#c2f35a]">Request accepted</div><div className="mt-2 text-lg">The workflow has been recorded.</div>{stage&&<div className="mt-2 text-xs text-[#8ca6ad]">Live stage: <span className="text-[#c2f35a]">{stage}</span></div>}<Progress value={progress}/><div className="mt-3 text-[10px] text-[#69858d]">No progress percentage is invented. The gauge appears only when the live service supplies one.</div></div>}
    <button disabled={!org||current?.admission_status!=="approved"} className="relative z-10 mt-6 w-full rounded-full border border-[#c2f35a]/50 bg-[#5f8e1f]/30 p-4 text-sm text-[#ddff9a] shadow-[0_14px_45px_rgba(194,243,90,.08)] transition hover:bg-[#6e9e25]/35 disabled:cursor-not-allowed disabled:opacity-35">Begin controlled workflow →</button>
   </form>}
  </div>
 </main>
}