"use client";
import {useEffect,useState} from "react";
import type {FormEvent} from "react";

import {getCustomerOrganizations,getCustomerVerification,apiFetch,type CustomerOrganization} from "../../lib/api";

const SERVICES=[["cybersecurity_assessment","Cybersecurity Assessment"],["incident_response","Incident Response"],["threat_intelligence","Threat Intelligence"],["dark_web_monitoring","Dark Web Monitoring"],["brand_protection","Brand Protection"],["soc_mdr","SOC / MDR"],["ai_security","AI Security"],["physical_security","Physical Security"],["compliance","Compliance"],["mobile_digital_intelligence","Mobile & Digital Intelligence"]];
const SERVICE_GUIDANCE:Record<string,{prompt:string;label:string;placeholder:string;help:string}>={
 cybersecurity_assessment:{prompt:"Identify the system, environment or business area you want assessed.",label:"System / environment",placeholder:"Website, application, cloud environment, network or business system",help:"Tell Cyclothone what is in scope and what you want the assessment to establish."},
 incident_response:{prompt:"Identify the incident or affected system and tell us what happened.",label:"Incident / affected system",placeholder:"Incident, domain, application, endpoint, account or affected system",help:"Add the known symptoms, timeframe and business impact below."},
 threat_intelligence:{prompt:"Give Cyclothone the indicator or threat context you want analyzed.",label:"Indicator / target",placeholder:"Domain, IP, hash, URL, email, actor or campaign",help:"Add the exact indicator where possible."},
 dark_web_monitoring:{prompt:"Choose the exact exposure you want Cyclothone to monitor.",label:"Target to monitor",placeholder:"example.com, brand name, email address, username or other approved target",help:"For a domain, enter the domain itself. For a brand, enter the exact brand name. Add multiple approved targets separated by commas."},
 brand_protection:{prompt:"Tell Cyclothone which brand or digital property you want protected.",label:"Brand / domain",placeholder:"Brand name or example.com",help:"Use the exact public brand name and/or domain you want monitored."},
 soc_mdr:{prompt:"Identify the environment Cyclothone should monitor and protect.",label:"Environment / system",placeholder:"Cloud, network, endpoint estate, application or other environment",help:"Add monitoring expectations, systems in scope and escalation requirements below."},
 ai_security:{prompt:"Identify the AI system, model or application that needs security review.",label:"AI system / model",placeholder:"AI application, model, agent, API or deployment",help:"Add the security objective, environment and known concerns below."},
 physical_security:{prompt:"Identify the authorized site or physical area that needs monitoring.",label:"Site / facility",placeholder:"Building, facility, site or authorized location",help:"Only submit locations you are authorized to monitor."},
 compliance:{prompt:"Identify the framework and the evidence or compliance outcome you need.",label:"Framework / objective",placeholder:"ISO 27001, SOC 2, PCI DSS, UAE PDPL, HIPAA…",help:"Add the scope, controls, audit date or evidence requirement below."},
 mobile_digital_intelligence:{prompt:"Identify the authorized mobile, device or digital target.",label:"Device / app / digital target",placeholder:"Device, application, account, domain or approved digital target",help:"Use an exact identifier where available and explain the objective below."}
};
const DEFAULT_GUIDANCE={prompt:"Describe the outcome you need Cyclothone to secure, investigate, monitor or assess.",label:"Target / scope",placeholder:"What should Cyclothone work on?",help:"Be specific about the target, scope and desired outcome."};

function Progress({value}:{value:number|null}){if(value===null)return null;return <div className="mt-5"><div className="mb-2 flex justify-between text-[9px] uppercase tracking-[.15em] text-[#67848d]"><span>Live workflow progress</span><span className="text-[#c2f35a]">{value}%</span></div><div className="cyclo-battery"><span style={{width:Math.max(0,Math.min(100,value))+"%"}}/></div></div>}

export default function RequestService(){
 const router=useRouter();
 const [orgs,setOrgs]=useState<CustomerOrganization[]>([]),[org,setOrg]=useState(""),[service,setService]=useState("cybersecurity_assessment"),[urgency,setUrgency]=useState("normal"),[target,setTarget]=useState(""),[description,setDescription]=useState(""),[verification,setVerification]=useState<any[]>([]),[error,setError]=useState<string|null>(null),[result,setResult]=useState<any>(null),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError(null);try{const r=await getCustomerOrganizations();setOrgs(r.organizations);const id=r.organizations[0]?.id||"";setOrg(id);if(id){const v=await getCustomerVerification(id);setVerification(v.verifications)}}catch(e){setError(e instanceof Error?e.message:"Unable to load organization")}finally{setLoading(false)}}
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get("service");if(requested&&SERVICES.some(x=>x[0]===requested))setService(requested);void load()},[]);
 async function selectOrg(id:string){setOrg(id);setError(null);try{const v=await getCustomerVerification(id);setVerification(v.verifications)}catch(e){setError(e instanceof Error?e.message:"Unable to load verification")}}
 async function requestAdmission(){setError(null);try{await apiFetch("/api/v1/customer/organizations/"+encodeURIComponent(org)+"/admission",{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"Admission request failed")}}
 async function submit(e:FormEvent){e.preventDefault();setError(null);setResult(null);try{const r=await apiFetch<any>("/api/v1/customer/service-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organization_id:org,service_key:service,urgency,description:[`Target: ${target.trim()}`,`Service objective: ${description.trim()}`].join("\n")})});setResult(r);setTarget("");setDescription("")}catch(e){setError(e instanceof Error?e.message:"Service request failed")}}
 const current=orgs.find(x=>x.id===org); const guidance=SERVICE_GUIDANCE[service]||DEFAULT_GUIDANCE; const serviceName=SERVICES.find(x=>x[0]===service)?.[1]||service;
 const progress=typeof result?.progress_percent==="number"?result.progress_percent:typeof result?.progress==="number"?result.progress:null;
 const stage=typeof result?.stage==="string"?result.stage:null;
 return <main className="cyclo-water min-h-screen overflow-hidden text-[#e8f1f3]">
  <header className="relative z-10 flex items-center justify-between border-b border-white/10 bg-[#02090e]/70 px-5 py-4 backdrop-blur-2xl"><div className="flex items-center gap-3"><a href="/customer/services" className="cyclo-mark text-lg font-bold">◌</a><a href="/customer/services" className="font-semibold tracking-tight">CYCLOTHONE</a></div><a href="/customer/services" className="cyclo-pill px-3 py-2 text-[10px] text-[#9ab0b6]">Back to services</a></header>
  <div className="relative z-10 mx-auto max-w-4xl px-5 py-10 md:py-14">
   <div className="text-[9px] uppercase tracking-[.22em] text-[#4f8494]">Controlled request</div><h1 className="mt-3 text-3xl font-semibold md:text-4xl">Start a security workflow.</h1><p className="mt-3 text-sm leading-7 text-[#8ca6ad]">Tell Cyclothone the outcome you need. The platform will route the request through the authorized service workflow. Progress is shown only when the live service returns a real stage or percentage.</p>
   {error&&<div className="mt-6 rounded-2xl border border-[#ff3d67]/30 bg-[#250910]/50 p-4 text-xs text-[#ff8ba0]">{error}</div>}
   {loading?<div className="mt-8 text-center text-xs text-[#69858d]">Reading organization state…</div>:!orgs.length?<div className="mt-8 rounded-[2rem] border border-dashed border-white/10 bg-[#031019]/70 p-9 text-center text-xs text-[#69858d]">No organization is available.<br/><a className="mt-3 inline-block text-[#c2f35a]" href="/customer/profile">Create one in Profile →</a></div>:
   <form onSubmit={submit} className="cyclo-node mt-8 p-6 shadow-[0_30px_100px_rgba(0,0,0,.35)] md:p-8">
    <label className="relative z-10 block text-xs font-medium">Organization<select required value={org} onChange={e=>void selectOrg(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-[#031019]/80 p-3.5 text-sm outline-none focus:border-[#c2f35a]/40">{orgs.map(o=><option key={o.id} value={o.id}>{o.legal_name} · {o.admission_status}</option>)}</select></label>
    <div className="cyclo-stage relative z-10 mt-4 p-4 text-xs text-[#8ca6ad]">Admission <strong className="text-[#e8f1f3]">{current?.admission_status}</strong> · Verification <strong className="text-[#e8f1f3]">{current?.verification_status}</strong>{current?.admission_status!=="approved"&&<div className="mt-3 text-[#ffd27a]">The workspace must be admitted before a protected request can be created. <a href="/customer/workspace" className="text-[#c2f35a]">View workspace →</a></div>}</div>
    <div className="cyclo-stage relative z-10 mt-4 p-4 text-xs text-[#8ca6ad]">Verification records: {verification.length?verification.map(v=>v.verification_type+":"+v.status).join(" · "):"none"}</div>
    <label className="relative z-10 mt-5 block text-xs font-medium">Service<select value={service} onChange={e=>setService(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-[#031019]/80 p-3.5 text-sm outline-none focus:border-[#c2f35a]/40">{SERVICES.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label>
    <div className="cyclo-stage relative z-10 mt-5 p-5"><div className="text-[9px] uppercase tracking-[.2em] text-[#4f8494]">Service brief · {serviceName}</div><p className="mt-2 text-sm text-[#dbe8ea]">{guidance.prompt}</p><p className="mt-2 text-[11px] leading-5 text-[#78939a]">{guidance.help}</p></div>\n    <label className="relative z-10 mt-5 block text-xs font-medium">{guidance.label}<input required minLength={2} maxLength={2000} value={target} onChange={e=>setTarget(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-[#031019]/80 p-3.5 text-sm outline-none focus:border-[#c2f35a]/40" placeholder={guidance.placeholder} /></label>\n    <label className="relative z-10 mt-5 block text-xs font-medium">Urgency<select value={urgency} onChange={e=>setUrgency(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-[#031019]/80 p-3.5 text-sm outline-none focus:border-[#c2f35a]/40">{["low","normal","high","critical"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label className="relative z-10 mt-5 block text-xs font-medium">What do you need?<textarea required minLength={10} maxLength={10000} value={description} onChange={e=>setDescription(e.target.value)} rows={7} className="mt-2 w-full rounded-2xl border border-white/10 bg-[#031019]/80 p-4 text-sm leading-6 outline-none focus:border-[#c2f35a]/40" placeholder="Add the context, scope, timeframe, systems, evidence or expected outcome. This stays attached to the target above." /></label>
    {result&&<div className="relative z-10 mt-5 rounded-2xl border border-[#c2f35a]/25 bg-[#b8ee4a]/5 p-5"><div className="text-[9px] uppercase tracking-[.18em] text-[#c2f35a]">Request accepted</div><div className="mt-2 text-lg">The workflow has been recorded.</div>{stage&&<div className="mt-2 text-xs text-[#8ca6ad]">Live stage: <span className="text-[#c2f35a]">{stage}</span></div>}<Progress value={progress}/><div className="mt-3 text-[10px] text-[#69858d]">No progress percentage is invented. The gauge appears only when the live service supplies one.</div></div>}
    <button disabled={!org||current?.admission_status!=="approved"} className="relative z-10 mt-6 w-full rounded-full border border-[#c2f35a]/50 bg-[#5f8e1f]/30 p-4 text-sm text-[#ddff9a] shadow-[0_14px_45px_rgba(194,243,90,.08)] transition hover:bg-[#6e9e25]/35 disabled:cursor-not-allowed disabled:opacity-35">Begin controlled workflow →</button>
   </form>}
  </div>
 </main>
}