"use client";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
const API=(process.env.NEXT_PUBLIC_SUPABASE_URL??"").replace(/\/$/,""),KEY=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY??"";
const SERVICES=[["cybersecurity_assessment","Cybersecurity Assessment"],["incident_response","Incident Response"],["threat_intelligence","Threat Intelligence"],["brand_protection","Brand Protection"],["dark_web_monitoring","Dark Web Monitoring"],["soc_mdr","SOC / MDR"],["ai_security","AI Security"],["physical_security","Physical Security"],["compliance","Compliance"],["other","Other"]];
export default function RequestService(){const router=useRouter();const [token,setToken]=useState(""),[user,setUser]=useState(""),[orgs,setOrgs]=useState<any[]>([]),[admission,setAdmission]=useState<any[]>([]),[verifications,setVerifications]=useState<any[]>([]),[org,setOrg]=useState(""),[service,setService]=useState("cybersecurity_assessment"),[urgency,setUrgency]=useState("normal"),[description,setDescription]=useState(""),[error,setError]=useState<string|null>(null),[ok,setOk]=useState(false);
useEffect(()=>{const t=sessionStorage.getItem("cyclothone_access_token")||"";if(!t){router.replace("/register");return}setToken(t);void load(t)},[]);
async function load(t:string){const h={"apikey":KEY,"Authorization":`Bearer ${t}`};const u=await fetch(API+"/auth/v1/user",{headers:h});if(!u.ok){router.replace("/register");return}const ub=await u.json();setUser(ub.id);const r=await fetch(API+"/rest/v1/customer_organizations?select=id,legal_name,organization_type,verification_status,admission_status&order=created_at.desc",{headers:h});const x=await r.json();if(!r.ok){setError(x.message||"Unable to load organizations");return}setOrgs(x);if(x[0]){setOrg(x[0].id);void loadVerification(t,x[0].id);void loadAdmission(t,x[0].id)}}
async function loadAdmission(t:string,id:string){const r=await fetch(API+"/rest/v1/organization_admissions?organization_id=eq."+id+"&select=status,assurance_level,submitted_at,reviewed_at&order=created_at.desc",{headers:{"apikey":KEY,"Authorization":`Bearer ${t}`}});if(r.ok)setAdmission(await r.json())}
async function requestAdmission(){setError(null);const r=await fetch(API+"/rest/v1/rpc/request_workspace_admission",{method:"POST",headers:{"apikey":KEY,"Authorization":`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({p_organization_id:org})});const raw=await r.text();if(!r.ok){let x:any={};try{x=JSON.parse(raw)}catch{}setError(x.message||raw||"Admission request failed");return}await loadAdmission(token,org)}
async function loadVerification(t:string,id:string){const r=await fetch(API+"/rest/v1/identity_verifications?organization_id=eq."+id+"&select=verification_type,status,submitted_at,verified_at",{headers:{"apikey":KEY,"Authorization":`Bearer ${t}`}});if(r.ok)setVerifications(await r.json())}
async function submit(e:FormEvent){e.preventDefault();setError(null);setOk(false);const r=await fetch(API+"/rest/v1/service_requests",{method:"POST",headers:{"apikey":KEY,"Authorization":`Bearer ${token}`,"Content-Type":"application/json","Prefer":"return=representation"},body:JSON.stringify({organization_id:org,requester_user_id:user,service_key:service,urgency,description})});const raw=await r.text();if(!r.ok){let x:any={};try{x=JSON.parse(raw)}catch{}setError(x.message||raw||"Service request failed");return}setOk(true);setDescription("")}
return <main className="min-h-screen bg-[#05070a] text-[#e8eef6]"><header className="border-b border-[#1a2330] px-6 py-4"><a href="/" className="font-semibold">Cyclothone</a></header><div className="mx-auto max-w-2xl px-6 py-12"><h1 className="text-3xl font-semibold">Request a security service</h1><p className="mt-2 text-sm text-[#8a97a8]">Your request is stored against your authenticated organization. No synthetic request is created.</p><form onSubmit={submit} className="mt-8 space-y-5 border border-[#1a2330] bg-[#0a0e14] p-6"><label className="block text-sm">Organization<select required value={org} onChange={e=>{setOrg(e.target.value);void loadVerification(token,e.target.value);void loadAdmission(token,e.target.value)}} className="mt-2 w-full border border-[#2a3646] bg-[#030508] p-3">{orgs.map(o=><option key={o.id} value={o.id}>{o.legal_name} · {o.verification_status}</option>)}</select></label><div className="border border-[#1a2330] p-3 text-xs text-[#8a97a8]">Workspace admission: {admission.length?admission[0].status:"not requested"} · {admission.length?admission[0].assurance_level:"registered"}<button type="button" onClick={requestAdmission} disabled={!org||admission.some(a=>a.status==="pending"||a.status==="review")} className="ml-3 border border-[#8a97a8] px-2 py-1 disabled:opacity-40">Request admission</button></div><div className="border border-[#1a2330] p-3 text-xs text-[#8a97a8]">Verification status: {verifications.length?verifications.map(v=>v.verification_type+":"+v.status).join(" · "):"No verification submitted"}</div><label className="block text-sm">Service<select value={service} onChange={e=>setService(e.target.value)} className="mt-2 w-full border border-[#2a3646] bg-[#030508] p-3">{SERVICES.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label className="block text-sm">Urgency<select value={urgency} onChange={e=>setUrgency(e.target.value)} className="mt-2 w-full border border-[#2a3646] bg-[#030508] p-3">{["low","normal","high","critical"].map(x=><option key={x}>{x}</option>)}</select></label><label className="block text-sm">Requirement<textarea required minLength={10} maxLength={10000} value={description} onChange={e=>setDescription(e.target.value)} rows={7} className="mt-2 w-full border border-[#2a3646] bg-[#030508] p-3" placeholder="Describe what you need Cyclothone to secure, investigate, monitor, or assess."/></label>{error&&<div className="border border-[#ff2d55]/40 p-3 text-sm text-[#ff6b83]">{error}</div>}{ok&&<div className="border border-[#00e07a]/30 p-3 text-sm text-[#7df0ad]">Service request submitted.</div>}<button disabled={!org} className="w-full border border-[#00d9ff] p-3 text-[#00d9ff] disabled:opacity-40">Submit service request</button></form></div></main>