import type { MdiCapability, ProviderAdapter } from './registry';
import type { SupabaseClient } from '@supabase/supabase-js';
export class TwilioLookupAdapter implements ProviderAdapter{
 slug='twilio_lookup';capabilities:MdiCapability[]=['carrier_lookup','line_type','sim_swap','number_reputation','kyc_match'];countries=['*'] as ['*'];
 constructor(private cfg:{accountSid:string;authToken:string;region?:string}){} private auth(){return 'Basic '+btoa(this.cfg.accountSid+':'+this.cfg.authToken);}
 async invoke<T>(cap:MdiCapability,params:Record<string,unknown>):Promise<T>{const phone=String(params.phoneNumber),host=this.cfg.region?'https://lookups.'+this.cfg.region+'.twilio.com':'https://lookups.twilio.com';const fields=cap==='sim_swap'?['sim_swap']:cap==='number_reputation'?['sms_pumping_risk','call_forwarding']:cap==='kyc_match'?['identity_match']:['line_type_intelligence'];const r=await fetch(host+'/v2/PhoneNumbers/'+encodeURIComponent(phone)+'?Fields='+fields.join(','),{headers:{authorization:this.auth()}});if(!r.ok)throw new Error('twilio_'+r.status);const j=await r.json();if(cap==='carrier_lookup'||cap==='line_type')return {carrier:j.line_type_intelligence?.carrier_name??null,lineType:(j.line_type_intelligence?.type??'unknown').toLowerCase(),mcc:j.line_type_intelligence?.mobile_country_code??null,mnc:j.line_type_intelligence?.mobile_network_code??null,valid:true,confidence:.9,raw:j} as T;if(cap==='sim_swap')return {swapped:!!j.sim_swap?.last_sim_swap?.last_sim_swap_date,lastSwapAt:j.sim_swap?.last_sim_swap?.last_sim_swap_date??null,confidence:.9,raw:j} as T;if(cap==='number_reputation')return {smsPumpingRisk:j.sms_pumping_risk?.sms_pumping_risk_score??0,callForwarding:j.call_forwarding?.call_forwarding_status==='true',complaints:0,confidence:.7,raw:j} as T;return {match:j.identity_match?.customer_name_match_score>=80,score:j.identity_match?.customer_name_match_score??0,confidence:.85,raw:j} as T;}
}
export class NumverifyAdapter implements ProviderAdapter{slug='numverify';capabilities:MdiCapability[]=['carrier_lookup','line_type'];countries=['*'] as ['*'];constructor(private apiKey:string){}async invoke<T>(cap:MdiCapability,params:Record<string,unknown>):Promise<T>{if(cap!=='carrier_lookup'&&cap!=='line_type')throw new Error('numverify_unsupported');const r=await fetch('https://apilayer.net/api/validate?access_key='+encodeURIComponent(this.apiKey)+'&number='+encodeURIComponent(String(params.phoneNumber))+'&format=1');if(!r.ok)throw new Error('numverify_'+r.status);const j=await r.json();return {valid:j.valid===true,carrier:j.carrier??null,lineType:(j.line_type??'unknown').toLowerCase(),countryIso2:j.country_code??null,confidence:.65,raw:j} as T;}}
export class InternalGraphAdapter implements ProviderAdapter{slug='internal_graph';capabilities:MdiCapability[]=['number_reputation'];countries=['*'] as ['*'];constructor(private sb:SupabaseClient){}async invoke<T>(cap:MdiCapability,params:Record<string,unknown>):Promise<T>{if(cap!=='number_reputation')throw new Error('internal_unsupported');const {data,error}=await this.sb.from('mdi_caller_reports').select('severity,verified,occurred_at').eq('subject_id',String(params.subjectId)).gte('occurred_at',new Date(Date.now()-180*86400_000).toISOString());if(error)throw error;const complaints=data?.length??0,verified=data?.filter((r:any)=>r.verified).length??0;return {complaints,verifiedComplaints:verified,confidence:complaints>=3?.9:.5,raw:{complaints,verified}} as T;}}
