"use client";
import {useState} from "react";
import {useParams} from "next/navigation";
import {apiFetch,setApiToken} from "../../../../../lib/api";
export default function CopilotPage(){
 const {service}=useParams<{service:string}>(); const [input,setInput]=useState(""); const [messages,setMessages]=useState<any[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const [threadId]=useState(()=>crypto.randomUUID());
 async function send(){if(!input.trim()||busy)return; const q=input.trim(); setInput(""); setMessages(m=>[...m,{role:"user",content:q}]); setBusy(true); setError("");
 try{setApiToken(sessionStorage.getItem("cyclothone_access_token")||""); const r=await apiFetch<any>("/api/v1/mobile-intelligence/copilot",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({thread_id:threadId,message:q})}); setMessages(m=>[...m,{role:"assistant",content:r.answer,citations:r.citations||[]}]);}
 catch(e){setError(e instanceof Error?e.message:"Copilot request failed");}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[#05070a] text-[#e8eef6] p-6"><div className="max-w-4xl mx-auto"><div className="mb-6"><div className="text-xs opacity-60">Cyclothone · MDI</div><h1 className="text-2xl font-semibold">Investigation Copilot</h1><p className="text-sm opacity-70">Evidence-backed investigation assistance. It does not authorize or execute actions.</p></div><div className="border border-[#1a2330] min-h-[55vh] p-4 space-y-3">{messages.length===0&&<div className="opacity-50">Ask a question about authorized MDI evidence.</div>}{messages.map((m,i)=><div key={i} className={m.role==="user"?"text-right":""}><div className="inline-block max-w-3xl border rounded px-3 py-2 text-left"><div>{m.content}</div>{m.citations?.length>0&&<div className="text-xs opacity-60 mt-2">{m.citations.map((c:any,j:number)=><span key={j} className="mr-2">[{c.kind}:{String(c.id).slice(0,8)}]</span>)}</div>}</div></div>)}{busy&&<div className="opacity-60">Investigating…</div>}</div><div className="flex gap-2 mt-3"><input className="flex-1 border bg-transparent rounded px-3 py-2" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask about this MDI evidence…" /><button className="border rounded px-4" onClick={send} disabled={busy}>Send</button></div>{error&&<div className="text-sm mt-2">{error}</div>}<div className="text-xs opacity-50 mt-3">{service==="mobile_digital_intelligence"?"":"Open this under the MDI service."}</div></div></main>
}