begin;
alter table public.mdi_providers enable row level security;
drop policy if exists mdi_providers_service_role on public.mdi_providers;
create policy mdi_providers_service_role on public.mdi_providers for all to service_role using(true) with check(true);
alter table public.mdi_operators enable row level security;
drop policy if exists mdi_operators_service_role on public.mdi_operators;
create policy mdi_operators_service_role on public.mdi_operators for all to service_role using(true) with check(true);
alter table public.mdi_subjects enable row level security;
drop policy if exists mdi_subjects_service_role on public.mdi_subjects;
create policy mdi_subjects_service_role on public.mdi_subjects for all to service_role using(true) with check(true);
alter table public.mdi_subject_aliases enable row level security;
drop policy if exists mdi_subject_aliases_service_role on public.mdi_subject_aliases;
create policy mdi_subject_aliases_service_role on public.mdi_subject_aliases for all to service_role using(true) with check(true);
alter table public.mdi_number_intel enable row level security;
drop policy if exists mdi_number_intel_service_role on public.mdi_number_intel;
create policy mdi_number_intel_service_role on public.mdi_number_intel for all to service_role using(true) with check(true);
alter table public.mdi_carrier_events enable row level security;
drop policy if exists mdi_carrier_events_service_role on public.mdi_carrier_events;
create policy mdi_carrier_events_service_role on public.mdi_carrier_events for all to service_role using(true) with check(true);
alter table public.mdi_imei_tac enable row level security;
drop policy if exists mdi_imei_tac_service_role on public.mdi_imei_tac;
create policy mdi_imei_tac_service_role on public.mdi_imei_tac for all to service_role using(true) with check(true);
alter table public.mdi_device_intel enable row level security;
drop policy if exists mdi_device_intel_service_role on public.mdi_device_intel;
create policy mdi_device_intel_service_role on public.mdi_device_intel for all to service_role using(true) with check(true);
alter table public.mdi_comms_events enable row level security;
drop policy if exists mdi_comms_events_service_role on public.mdi_comms_events;
create policy mdi_comms_events_service_role on public.mdi_comms_events for all to service_role using(true) with check(true);
alter table public.mdi_caller_reports enable row level security;
drop policy if exists mdi_caller_reports_service_role on public.mdi_caller_reports;
create policy mdi_caller_reports_service_role on public.mdi_caller_reports for all to service_role using(true) with check(true);
alter table public.mdi_location_signals enable row level security;
drop policy if exists mdi_location_signals_service_role on public.mdi_location_signals;
create policy mdi_location_signals_service_role on public.mdi_location_signals for all to service_role using(true) with check(true);
alter table public.mdi_geofences enable row level security;
drop policy if exists mdi_geofences_service_role on public.mdi_geofences;
create policy mdi_geofences_service_role on public.mdi_geofences for all to service_role using(true) with check(true);
alter table public.mdi_satellites enable row level security;
drop policy if exists mdi_satellites_service_role on public.mdi_satellites;
create policy mdi_satellites_service_role on public.mdi_satellites for all to service_role using(true) with check(true);
alter table public.mdi_satellite_passes enable row level security;
drop policy if exists mdi_satellite_passes_service_role on public.mdi_satellite_passes;
create policy mdi_satellite_passes_service_role on public.mdi_satellite_passes for all to service_role using(true) with check(true);
alter table public.mdi_satellite_observations enable row level security;
drop policy if exists mdi_satellite_observations_service_role on public.mdi_satellite_observations;
create policy mdi_satellite_observations_service_role on public.mdi_satellite_observations for all to service_role using(true) with check(true);
alter table public.mdi_graph_edges enable row level security;
drop policy if exists mdi_graph_edges_service_role on public.mdi_graph_edges;
create policy mdi_graph_edges_service_role on public.mdi_graph_edges for all to service_role using(true) with check(true);
alter table public.mdi_correlations enable row level security;
drop policy if exists mdi_correlations_service_role on public.mdi_correlations;
create policy mdi_correlations_service_role on public.mdi_correlations for all to service_role using(true) with check(true);
alter table public.mdi_risk_assessments enable row level security;
drop policy if exists mdi_risk_assessments_service_role on public.mdi_risk_assessments;
create policy mdi_risk_assessments_service_role on public.mdi_risk_assessments for all to service_role using(true) with check(true);
alter table public.mdi_provider_calls enable row level security;
drop policy if exists mdi_provider_calls_service_role on public.mdi_provider_calls;
create policy mdi_provider_calls_service_role on public.mdi_provider_calls for all to service_role using(true) with check(true);
alter table public.mdi_case_links enable row level security;
drop policy if exists mdi_case_links_service_role on public.mdi_case_links;
create policy mdi_case_links_service_role on public.mdi_case_links for all to service_role using(true) with check(true);
revoke execute on function public.mdi_upsert_subject(public.mdi_subject_kind,text,text,char(2),jsonb,smallint) from anon,authenticated;
revoke execute on function public.mdi_link(uuid,uuid,public.mdi_edge_kind,numeric,numeric,uuid,text,jsonb) from anon,authenticated;
revoke execute on function public.mdi_refresh_risk(uuid) from anon,authenticated;
commit;