"use client";
import {useEffect,useState} from "react";
import {apiFetch} from "../../../../lib/api";
type R=Record<string,any>;
export default function Hunting(){const[h,setH]=useState<R[]>([]),[runs,setRuns]=useState<R[]>([]),[q,setQ]=useState(""),[out,setOut]=useState<any>(null),[e,setE]=useState("");
const load=()=>Promise.all([apiFetch<any>("/api/v1/hunts/"),apiFetch<any>("/api/v1/hunts/runs/history")]).then(([a,b])=>{setH(a);setRuns(b)}).catch(x=>setE(x.message));
useEffect(()=>{void load()},[]);
async function run(){setE("");try{if(!q.trim())throw new Error("Query required");setOut(await apiFetch("/api/v1/hunts/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:q})}));await load()}catch(x){setE(x instanceof Error?x.message:"Hunt failed")}}
return <main className="min-h-screen bg-[#05070a] p-6 text-[#e8eef6]"><div className="mx-auto max-w-6xl space-y-5"><header><div className="text-[10px] uppercase tracking-[.16em] text-[#5a6675]">Assurance</div><h1 className="mt-1 text-2xl font-semibold">Threat Hunting</h1><p className="mt-1 text-xs text-[#8a97a8]">Execute the bounded hunting language and retain run telemetry.</p></header><section className="border border-[#1a2330] bg-[#0a0e14] p-5"><textarea value={q} onChange={e=>setQ(e.target.value)} rows={5} placeholder="Enter hunting query" className="w-full border border-[#2a3646] bg-[#030508] p-3 text-xs"/><button onClick={()=>void run()} className="mt-3 h-9 border border-[#00d9ff] px-4 text-xs text-[#00d9ff]">Run hunt</button>{e&&<div className="mt-3 text-xs text-[#ff6b83]">{e}</div>}{out&&<pre className="mt-4 max-h-80 overflow-auto text-xs">{JSON.stringify(out,null,2)}</pre>}</section><section className="border border-[#1a2330] bg-[#0a0e14] p-5"><h2>Saved hunts ({h.length})</h2><pre className="mt-3 max-h-72 overflow-auto text-xs">{JSON.stringify(h,null,2)}</pre></section><section className="border border-[#1a2330] bg-[#0a0e14] p-5"><h2>Run history ({runs.length})</h2><pre className="mt-3 max-h-72 overflow-auto text-xs">{JSON.stringify(runs,null,2)}</pre></section></div></main>
}