-- Sentinel Threat Hunting Workbench, migration 026.
-- Saved hunts, execution history, and tenant-scoped schedules.

create table if not exists public.hunts (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null references public.tenants(id) on delete cascade,
    name text not null check (length(trim(name)) between 1 and 200),
    description text,
    query text not null check (length(query) between 4 and 8000),
    params jsonb not null default '{}'::jsonb,
    tags text[] not null default '{}'::text[],
    is_template boolean not null default false,
    is_public boolean not null default false,
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    last_run_at timestamptz,
    run_count integer not null default 0 check (run_count >= 0)
);
create index if not exists idx_hunts_tenant_updated on public.hunts(tenant_id, updated_at desc);
create index if not exists idx_hunts_tags on public.hunts using gin(tags);
create index if not exists idx_hunts_templates on public.hunts(tenant_id, is_template) where is_template = true;

create table if not exists public.hunt_runs (
    id bigint generated by default as identity primary key,
    tenant_id uuid not null references public.tenants(id) on delete cascade,
    hunt_id uuid references public.hunts(id) on delete set null,
    query text not null check (length(query) between 4 and 8000),
    status text not null default 'running' check (status in ('running','success','failed','timeout')),
    rows_returned integer check (rows_returned is null or rows_returned >= 0),
    duration_ms integer check (duration_ms is null or duration_ms >= 0),
    error text,
    triggered_by text not null default 'user' check (triggered_by in ('user','schedule','alert')),
    ran_by uuid references auth.users(id) on delete set null,
    started_at timestamptz not null default now(),
    ended_at timestamptz
);
create index if not exists idx_hunt_runs_tenant_started on public.hunt_runs(tenant_id, started_at desc);
create index if not exists idx_hunt_runs_hunt_started on public.hunt_runs(hunt_id, started_at desc);

create table if not exists public.hunt_schedules (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null references public.tenants(id) on delete cascade,
    hunt_id uuid not null references public.hunts(id) on delete cascade,
    cron text not null check (length(trim(cron)) between 5 and 120),
    enabled boolean not null default true,
    auto_case boolean not null default true,
    severity text not null default 'medium' check (severity in ('low','medium','high','critical')),
    category text not null default 'other' check (length(trim(category)) between 1 and 80),
    last_run_at timestamptz,
    created_at timestamptz not null default now()
);
create index if not exists idx_hunt_schedules_tenant_enabled on public.hunt_schedules(tenant_id, enabled);

alter table public.hunts enable row level security;
alter table public.hunt_runs enable row level security;
alter table public.hunt_schedules enable row level security;

drop policy if exists hunts_tenant_select on public.hunts;
create policy hunts_tenant_select on public.hunts
    for select to authenticated
    using (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

drop policy if exists hunt_runs_tenant_select on public.hunt_runs;
create policy hunt_runs_tenant_select on public.hunt_runs
    for select to authenticated
    using (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

drop policy if exists hunt_schedules_tenant_select on public.hunt_schedules;
create policy hunt_schedules_tenant_select on public.hunt_schedules
    for select to authenticated
    using (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

-- All hunt mutations and execution are performed by the Sentinel service role.
revoke all on public.hunts, public.hunt_runs, public.hunt_schedules from anon, authenticated;

create or replace function public.touch_hunt_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists hunts_touch_updated_at on public.hunts;
create trigger hunts_touch_updated_at
before update on public.hunts
for each row execute function public.touch_hunt_updated_at();
revoke all on function public.touch_hunt_updated_at() from public, anon, authenticated;

grant select on public.hunts, public.hunt_runs, public.hunt_schedules to authenticated;
grant all on public.hunts, public.hunt_runs, public.hunt_schedules to service_role;
