-- Cyclothone Time Machine durable snapshot-chain foundation.
-- Migration number intentionally follows existing 056 Honeynet Mesh.
-- No live migration is performed by this commit.

create table if not exists tm_snapshots (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null references tenants(id) on delete cascade,
    scope text not null check (scope in ('tenant','device','entity','case','account')),
    scope_ref text,
    snapshot_ts timestamptz not null,
    state jsonb not null,
    state_sha256 text not null check (state_sha256 ~ '^[0-9a-fA-F]{64}$'),
    event_count integer not null default 0 check (event_count >= 0),
    prev_snapshot uuid references tm_snapshots(id) on delete set null,
    chain_id uuid not null,
    chain_seq integer not null check (chain_seq >= 1),
    created_at timestamptz not null default now(),
    unique (tenant_id, scope, scope_ref, snapshot_ts)
);

create index if not exists idx_tm_snap_tenant_ts
    on tm_snapshots(tenant_id, snapshot_ts desc);
create index if not exists idx_tm_snap_scope
    on tm_snapshots(tenant_id, scope, scope_ref, snapshot_ts desc);
create index if not exists idx_tm_snap_chain
    on tm_snapshots(tenant_id, chain_id, chain_seq);

create table if not exists tm_deltas (
    id bigint generated by default as identity primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    chain_id uuid not null,
    from_snapshot uuid references tm_snapshots(id) on delete set null,
    to_snapshot uuid references tm_snapshots(id) on delete set null,
    scope text not null check (scope in ('tenant','device','entity','case','account')),
    scope_ref text,
    delta_ts timestamptz not null,
    operations jsonb not null check (jsonb_typeof(operations) = 'array'),
    event_ids text[] not null default '{}',
    created_at timestamptz not null default now()
);

create index if not exists idx_tm_delta_chain
    on tm_deltas(tenant_id, chain_id, delta_ts);
create index if not exists idx_tm_delta_scope
    on tm_deltas(tenant_id, scope, scope_ref, delta_ts);
create index if not exists idx_tm_delta_tenant
    on tm_deltas(tenant_id, delta_ts desc);

create table if not exists tm_replays (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null references tenants(id) on delete cascade,
    scope text not null check (scope in ('tenant','device','entity','case','account')),
    scope_ref text,
    from_ts timestamptz not null,
    to_ts timestamptz not null check (to_ts > from_ts),
    step_ms integer not null default 1000 check (step_ms between 100 and 60000),
    status text not null default 'pending'
        check (status in ('pending','running','complete','failed')),
    frame_count integer check (frame_count is null or frame_count >= 0),
    frames_ref text,
    requested_by uuid references auth.users(id) on delete set null,
    error text,
    created_at timestamptz not null default now(),
    completed_at timestamptz
);

create index if not exists idx_tm_replay_tenant
    on tm_replays(tenant_id, created_at desc);

alter table tm_snapshots enable row level security;
alter table tm_deltas enable row level security;
alter table tm_replays enable row level security;

drop policy if exists tm_snapshots_tenant_select on tm_snapshots;
create policy tm_snapshots_tenant_select on tm_snapshots
    for select to authenticated
    using (tenant_id = (select (auth.jwt() ->> 'tenant_id')::uuid));

drop policy if exists tm_deltas_tenant_select on tm_deltas;
create policy tm_deltas_tenant_select on tm_deltas
    for select to authenticated
    using (tenant_id = (select (auth.jwt() ->> 'tenant_id')::uuid));

drop policy if exists tm_replays_tenant_select on tm_replays;
create policy tm_replays_tenant_select on tm_replays
    for select to authenticated
    using (tenant_id = (select (auth.jwt() ->> 'tenant_id')::uuid));

revoke all on tm_snapshots from anon, authenticated;
revoke all on tm_deltas from anon, authenticated;
revoke all on tm_replays from anon, authenticated;

-- Service-only atomic snapshot recording.
-- The advisory transaction lock serializes writers for one tenant/scope/ref/chain,
-- preventing duplicate chain_seq/prev_snapshot under concurrent workers.
create or replace function tm_record_snapshot(
    p_tenant uuid,
    p_scope text,
    p_scope_ref text,
    p_snapshot_ts timestamptz,
    p_state jsonb,
    p_state_sha text,
    p_event_count integer,
    p_chain_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
    v_id uuid;
    v_prev uuid;
    v_seq integer;
    v_key text;
begin
    if p_tenant is null or not exists (
        select 1 from tenants where id = p_tenant
    ) then
        raise exception 'invalid tenant';
    end if;

    if p_scope not in ('tenant','device','entity','case','account') then
        raise exception 'invalid scope';
    end if;

    if p_snapshot_ts is null or p_state is null or p_chain_id is null then
        raise exception 'snapshot fields cannot be null';
    end if;

    if p_event_count is null or p_event_count < 0 then
        raise exception 'event_count must be nonnegative';
    end if;

    if p_state_sha is null or p_state_sha !~ '^[0-9a-fA-F]{64}$' then
        raise exception 'invalid state_sha256';
    end if;

    v_key := concat(
        p_tenant::text, ':', p_scope, ':',
        coalesce(p_scope_ref, ''), ':', p_chain_id::text
    );
    perform pg_advisory_xact_lock(hashtextextended(v_key, 0));

    select id, chain_seq
      into v_prev, v_seq
      from tm_snapshots
     where tenant_id = p_tenant
       and scope = p_scope
       and coalesce(scope_ref, '') = coalesce(p_scope_ref, '')
       and chain_id = p_chain_id
     order by snapshot_ts desc, created_at desc, id desc
     limit 1
     for update;

    v_seq := coalesce(v_seq, 0) + 1;

    insert into tm_snapshots (
        tenant_id, scope, scope_ref, snapshot_ts, state, state_sha256,
        event_count, prev_snapshot, chain_id, chain_seq
    )
    values (
        p_tenant, p_scope, p_scope_ref, p_snapshot_ts, p_state, lower(p_state_sha),
        p_event_count, v_prev, p_chain_id, v_seq
    )
    on conflict (tenant_id, scope, scope_ref, snapshot_ts)
    do update set
        state = excluded.state,
        state_sha256 = excluded.state_sha256,
        event_count = excluded.event_count
    returning id into v_id;

    return v_id;
end;
$$;

revoke all on function tm_record_snapshot(uuid,text,text,timestamptz,jsonb,text,integer,uuid)
    from public, anon, authenticated;
grant execute on function tm_record_snapshot(uuid,text,text,timestamptz,jsonb,text,integer,uuid)
    to service_role;

create or replace function tm_nearest_snapshot(
    p_tenant uuid,
    p_scope text,
    p_scope_ref text,
    p_ts timestamptz
)
returns uuid
language sql
stable
security definer
set search_path = public
as $$
    select id
      from tm_snapshots
     where tenant_id = p_tenant
       and scope = p_scope
       and coalesce(scope_ref, '') = coalesce(p_scope_ref, '')
       and snapshot_ts <= p_ts
     order by snapshot_ts desc, created_at desc, id desc
     limit 1;
$$;

revoke all on function tm_nearest_snapshot(uuid,text,text,timestamptz)
    from public, anon, authenticated;
grant execute on function tm_nearest_snapshot(uuid,text,text,timestamptz)
    to service_role;

comment on table tm_snapshots is 'Immutable time-machine state checkpoints; mutations occur only through service-role functions.';
comment on table tm_deltas is 'Tenant-scoped state deltas used to reconstruct checkpoints.';
comment on table tm_replays is 'Tenant-scoped replay job metadata; frame bundles remain externalized.';
