-- sql/061_predictive.sql
-- Predictive Containment foundation. Service mutation boundary; tenant-derived reads.
begin;

create table if not exists attack_patterns (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid references tenants(id) on delete cascade,
    name text not null check (length(name) between 1 and 200),
    sequence text[] not null check (cardinality(sequence) between 1 and 32),
    occurrences bigint not null default 1 check (occurrences > 0),
    avg_hops real not null default 2.0 check (avg_hops >= 0 and avg_hops <= 32),
    avg_dwell_sec bigint not null default 300 check (avg_dwell_sec >= 0),
    success_rate real not null default 0.5 check (success_rate between 0 and 1),
    relation_weights jsonb not null default '{}'::jsonb,
    mitre_chain text[] not null default '{}',
    first_seen timestamptz not null default now(),
    last_seen timestamptz not null default now(),
    unique (tenant_id, name)
);
create index if not exists idx_attack_patterns_tenant on attack_patterns(tenant_id, occurrences desc);

create table if not exists compromise_markers (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null references tenants(id) on delete cascade,
    source_kind text not null check (source_kind in ('detection','honeypot_touch','canary','ato','chain_hit','manual')),
    source_id text not null check (length(source_id) between 1 and 256),
    case_id uuid references crime_cases(id) on delete set null,
    node_id uuid,
    node_external text check (node_external is null or length(node_external) <= 512),
    node_type text not null check (length(node_type) between 1 and 64),
    confidence real not null default 0.8 check (confidence between 0 and 1),
    status text not null default 'active' check (status in ('active','contained','resolved','false_positive')),
    detected_at timestamptz not null default now(),
    resolved_at timestamptz,
    unique (tenant_id, source_kind, source_id, node_id)
);
create index if not exists idx_comp_marker_tenant on compromise_markers(tenant_id, status, detected_at desc);
create index if not exists idx_comp_marker_node on compromise_markers(tenant_id, node_id);

create table if not exists attack_predictions (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null references tenants(id) on delete cascade,
    marker_id uuid not null references compromise_markers(id) on delete cascade,
    case_id uuid references crime_cases(id) on delete set null,
    model_kind text not null default 'graph_path_v1' check (length(model_kind) between 1 and 64),
    horizon_hops int not null default 3 check (horizon_hops between 1 and 5),
    top_targets int not null default 0 check (top_targets >= 0),
    confidence real not null default 0 check (confidence between 0 and 1),
    duration_ms int check (duration_ms is null or duration_ms >= 0),
    created_at timestamptz not null default now()
);
create index if not exists idx_predictions_tenant on attack_predictions(tenant_id, created_at desc);

create table if not exists predicted_targets (
    id uuid primary key default gen_random_uuid(),
    prediction_id uuid not null references attack_predictions(id) on delete cascade,
    tenant_id uuid not null references tenants(id) on delete cascade,
    node_id uuid not null,
    node_external text,
    node_type text not null,
    hops int not null check (hops between 1 and 5),
    prior_score real not null default 0 check (prior_score between 0 and 1),
    likelihood real not null default 0 check (likelihood between 0 and 1),
    impact real not null default 0 check (impact between 0 and 1),
    combined real not null default 0 check (combined between 0 and 1),
    path jsonb not null default '[]'::jsonb,
    preempted boolean not null default false,
    preempt_action text,
    attacker_arrived boolean,
    arrived_at timestamptz,
    created_at timestamptz not null default now()
);
create index if not exists idx_pt_prediction on predicted_targets(prediction_id, combined desc);
create index if not exists idx_pt_tenant on predicted_targets(tenant_id, preempted);
create index if not exists idx_pt_arrival on predicted_targets(tenant_id, attacker_arrived) where attacker_arrived = true;

create table if not exists preempt_actions (
    id bigint generated by default as identity primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    predicted_target_id uuid not null references predicted_targets(id) on delete cascade,
    kind text not null check (kind in ('micro_segment','force_mfa','rotate_credentials','monitoring_boost','snapshot_now','block_lateral','isolate_preemptively','quarantine_preemptively')),
    status text not null default 'deployed' check (status in ('planned','dispatched','deployed','failed','rolled_back')),
    reversible boolean not null default true,
    rollback_args jsonb,
    reason text check (reason is null or length(reason) <= 2000),
    command_id uuid,
    created_at timestamptz not null default now()
);
create index if not exists idx_preempt_tenant on preempt_actions(tenant_id, created_at desc);

alter table attack_patterns enable row level security;
alter table compromise_markers enable row level security;
alter table attack_predictions enable row level security;
alter table predicted_targets enable row level security;
alter table preempt_actions enable row level security;

drop policy if exists attack_patterns_read on attack_patterns;
create policy attack_patterns_read on attack_patterns for select to authenticated
using (tenant_id is null or tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

drop policy if exists comp_marker_tenant on compromise_markers;
create policy comp_marker_tenant on compromise_markers for select to authenticated
using (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

drop policy if exists predictions_tenant on attack_predictions;
create policy predictions_tenant on attack_predictions for select to authenticated
using (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

drop policy if exists pt_tenant on predicted_targets;
create policy pt_tenant on predicted_targets for select to authenticated
using (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

drop policy if exists preempt_tenant on preempt_actions;
create policy preempt_tenant on preempt_actions for select to authenticated
using (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

revoke all on attack_patterns, compromise_markers, attack_predictions, predicted_targets, preempt_actions from anon, authenticated;

-- Revoke table access first; API routes use the service boundary.
revoke all on attack_patterns, compromise_markers, attack_predictions, predicted_targets, preempt_actions from anon, authenticated;

create or replace function predict_upsert_marker(
    p_tenant uuid, p_source_kind text, p_source_id text, p_case uuid,
    p_node uuid, p_node_ext text, p_node_type text, p_confidence real
) returns uuid
language plpgsql security definer set search_path = public
as $$
declare v_id uuid;
begin
    if p_tenant is null or p_source_id is null or length(p_source_id) not between 1 and 256
       or p_node_type is null or length(p_node_type) not between 1 and 64
       or p_confidence is null or p_confidence < 0 or p_confidence > 1 then
        raise exception 'invalid predictive marker';
    end if;
    insert into compromise_markers
      (tenant_id, source_kind, source_id, case_id, node_id, node_external, node_type, confidence)
    values
      (p_tenant, p_source_kind, p_source_id, p_case, p_node, p_node_ext, p_node_type, p_confidence)
    on conflict (tenant_id, source_kind, source_id, node_id) do update
      set confidence = greatest(compromise_markers.confidence, excluded.confidence),
          detected_at = least(compromise_markers.detected_at, excluded.detected_at),
          status = case when compromise_markers.status = 'false_positive'
                        then 'active' else compromise_markers.status end,
          resolved_at = case when compromise_markers.status = 'false_positive'
                             then null else compromise_markers.resolved_at end
    returning id into v_id;
    return v_id;
end;
$$;

create or replace function predict_record_outcome(
    p_tenant uuid, p_target uuid, p_arrived boolean
) returns void
language plpgsql security definer set search_path = public
as $$
begin
    update predicted_targets
       set attacker_arrived = p_arrived,
           arrived_at = case when p_arrived then coalesce(arrived_at, now()) else arrived_at end
     where id = p_target and tenant_id = p_tenant;
    if not found then raise exception 'prediction target not found'; end if;
end;
$$;

create or replace function predict_stats(p_tenant uuid)
returns jsonb language sql stable security definer set search_path = public
as $$
select jsonb_build_object(
 'active_compromises', (select count(*) from compromise_markers where tenant_id=p_tenant and status='active'),
 'predictions_24h', (select count(*) from attack_predictions where tenant_id=p_tenant and created_at > now()-interval '24 hours'),
 'preempted_targets', (select count(*) from predicted_targets where tenant_id=p_tenant and preempted),
 'attacker_arrivals', (select count(*) from predicted_targets where tenant_id=p_tenant and attacker_arrived),
 'preempted_arrivals', (select count(*) from predicted_targets where tenant_id=p_tenant and preempted and attacker_arrived),
 'hit_rate', coalesce(
   (select count(*)::numeric from predicted_targets where tenant_id=p_tenant and preempted and attacker_arrived) /
   nullif((select count(*)::numeric from predicted_targets where tenant_id=p_tenant and preempted),0), 0)
);
$$;

revoke all on function predict_upsert_marker(uuid,text,text,uuid,uuid,text,text,real) from public;
revoke all on function predict_record_outcome(uuid,uuid,boolean) from public;
revoke all on function predict_stats(uuid) from public;
grant execute on function predict_upsert_marker(uuid,text,text,uuid,uuid,text,text,real) to service_role;
grant execute on function predict_record_outcome(uuid,uuid,boolean) to service_role;
grant execute on function predict_stats(uuid) to service_role;

commit;
