-- 134_trust_measurement_snapshot_integrity.sql
create table if not exists public.trust_measurement_snapshots(
 id uuid primary key default gen_random_uuid(),tenant_id uuid references public.tenants(id) on delete cascade,
 subject_id uuid not null references public.trust_subjects(id) on delete restrict,through_time timestamptz not null,
 measurement_count integer not null,snapshot_hash text not null check(snapshot_hash ~ '^[0-9a-f]{64}$'),created_at timestamptz not null default now(),
 unique(subject_id,through_time,snapshot_hash));
alter table public.trust_measurement_snapshots enable row level security;
revoke all on public.trust_measurement_snapshots from public,anon,authenticated;grant select on public.trust_measurement_snapshots to authenticated;
create policy trust_measurement_snapshots_member_read on public.trust_measurement_snapshots for select to authenticated using(tenant_id is null or exists(select 1 from public.tenant_members tm where tm.tenant_id=trust_measurement_snapshots.tenant_id and tm.user_id=auth.uid()));
create or replace function public.trust_measurement_snapshot_hash(p_subject_id uuid,p_through timestamptz) returns text language sql stable set search_path=public,pg_catalog as $$
select encode(extensions.digest(convert_to(coalesce(jsonb_agg(jsonb_build_object('id',m.id,'sequence_no',m.sequence_no,'measurement_hash',m.measurement_hash,'measurement_type',m.measurement_type,'algorithm',m.algorithm,'measurement_value',m.measurement_value,'source_type',m.source_type,'source_id',m.source_id,'collected_at',m.collected_at,'received_at',m.received_at,'evidence_uri',m.evidence_uri,'evidence_hash',m.evidence_hash,'metadata',m.metadata,'created_at',m.created_at) order by m.sequence_no,m.id),'[]'::jsonb)::text,'UTF8'),'sha256'),'hex') from public.trust_measurements m where m.subject_id=p_subject_id and m.created_at<=p_through$$;
create or replace function public.trust_record_measurement_snapshot(p_subject_id uuid,p_through timestamptz default now()) returns public.trust_measurement_snapshots language plpgsql security definer set search_path=public,pg_catalog as $$
declare s public.trust_subjects;r public.trust_measurement_snapshots;h text;c int;
begin select * into s from public.trust_subjects where id=p_subject_id;if not found then raise exception 'trust_subject_not_found';end if;h:=public.trust_measurement_snapshot_hash(p_subject_id,p_through);select count(*)::int into c from public.trust_measurements where subject_id=p_subject_id and created_at<=p_through;insert into public.trust_measurement_snapshots(tenant_id,subject_id,through_time,measurement_count,snapshot_hash) values(s.tenant_id,p_subject_id,p_through,c,h) on conflict(subject_id,through_time,snapshot_hash) do nothing returning * into r;if r.id is null then select * into r from public.trust_measurement_snapshots where subject_id=p_subject_id and through_time=p_through and snapshot_hash=h limit 1;end if;return r;end$$;
revoke all on function public.trust_record_measurement_snapshot(uuid,timestamptz) from public,anon,authenticated;grant execute on function public.trust_record_measurement_snapshot(uuid,timestamptz) to service_role;
create or replace function public.trust_verify_measurement_snapshot(p_snapshot_id uuid) returns boolean language plpgsql security definer set search_path=public,pg_catalog as $$
declare s public.trust_measurement_snapshots;h text;c int;
begin select * into s from public.trust_measurement_snapshots where id=p_snapshot_id;if not found then raise exception 'measurement_snapshot_not_found';end if;h:=public.trust_measurement_snapshot_hash(s.subject_id,s.through_time);select count(*)::int into c from public.trust_measurements where subject_id=s.subject_id and created_at<=s.through_time;return h=s.snapshot_hash and c=s.measurement_count;end$$;
revoke all on function public.trust_verify_measurement_snapshot(uuid) from public,anon,authenticated;grant execute on function public.trust_verify_measurement_snapshot(uuid) to service_role;
create or replace function public.trust_measurement_root(p_subject_id uuid,p_through timestamptz) returns text language sql stable set search_path=public,pg_catalog as $$select public.trust_measurement_snapshot_hash(p_subject_id,p_through)$$;